In [1]:
# Libraries
import pandas as pd
import requests
from multiprocessing.pool import ThreadPool as Pool
from tqdm.notebook import tqdm
import json

In [ ]:
# Reading the data
data = pd.read_csv("data\Mastodon_instances_edges_Sept2024.csv")
data.head()

<>:1: SyntaxWarning: invalid escape sequence '\M'
<>:1: SyntaxWarning: invalid escape sequence '\M'
C:\Users\alelc\AppData\Local\Temp\ipykernel_28188\4284201516.py:1: SyntaxWarning: invalid escape sequence '\M'
  data = pd.read_csv("data\Mastodon_instances_edges_Sept2024.csv")

            source_domain           target_domain   weight
0              baraag.net              baraag.net  5048993
1         mastodon.social         mastodon.social  1156269
2            mastodon.uno            mastodon.uno   602899
3  mastodon.gamedev.place  mastodon.gamedev.place   344733
4               pawoo.net              baraag.net   305426

In [3]:
data.shape

(1734054, 3)

In [ ]:
# Removing self-loops
data = data[data['source_domain'] != data['target_domain']]
print(f"Dataset shape after removing self-loops: {data.shape}")

Dataset shape after removing self-loops: (1731393, 3)

In [5]:
data.shape

(1731393, 3)

In [ ]:
# Filtering the data
data = data[data['weight'] >= 10]
print(data.shape)

(217879, 3)

In [ ]:
# Saving the filtered data
data.to_csv("data/Mastodon_instances_edges_Sept2024_filtered.csv", index=False)

In [ ]:
import regex as re
from bs4 import BeautifulSoup

# Method for cleaning text
def clean_html(text):
    # Step 1: Parse HTML content
    soup = BeautifulSoup(text, "html.parser")

    # Step 2: Extract plain text from the parsed HTML (this also removes tags)
    clean_text = soup.get_text()

    # Step 3: Remove emojis using a regular expression
    # This regex allows all alphabets (any script), numbers, and spaces but removes emojis and symbols.
    clean_text = re.sub(r'[^\p{L}\p{N}\s]+', '', clean_text)  # \p{L} matches any letter, \p{N} matches any number

    # Step 4: Remove extra spaces, newlines, and tabs
    clean_text = re.sub(r'\s+', ' ', clean_text).strip()

    return clean_text

In [10]:
def get_instance_info(instance):
    # Preparing the target URL
    info_url = f'https://{instance}/api/v2/instance'

    # Asking for instance metadata
    try:
        # Performing the request
        response = requests.get(info_url, timeout=(19,10))

        # Checking for the status code
        if response.status_code == requests.codes.ok:
            # If ok get the json
            parsed_response = json.loads(response.text)
            parsed_rules = [rule['text'] for rule in parsed_response['rules']]

            active_users = parsed_response['usage']['users']['active_month']
            if active_users <= 0:
                return (instance, None, None)
            
            # Additional API call for extended description
            extended_desc_detailed = None
            try:
                # Preparing the target URL for extended description
                ext_desc_url = f'https://{instance}/api/v1/instance/extended_description'
                
                # Performing the request
                ext_response = requests.get(ext_desc_url, timeout=30)
                
                # Checking for the status code
                if ext_response.status_code == requests.codes.ok:
                    # If ok get the json
                    ext_parsed_response = json.loads(ext_response.text)
                    extended_desc_detailed = clean_html(ext_parsed_response['content'])
                    print(f"Extended description found for {instance}")
                
                # 404 means no ext. description was declared
                elif ext_response.status_code == 404:
                    print(f"{instance} didn't declare any extended description!")
                    extended_desc_detailed = None
                    
            except Exception as e:
                print(f"The following error occurred while asking for {instance}'s extended description: {e}")
                extended_desc_detailed = None
            
            return (instance, parsed_response['title'], clean_html(parsed_response['description']), extended_desc_detailed,
                    parsed_response['version'], parsed_response['source_url'], 
                    active_users, parsed_rules)

    except Exception as e:
        print(f"Error for instance: {instance}")
        print(e)
        return (instance, None, None)

In [11]:
# Test
get_instance_info("planetearth.social")

Extended description found for planetearth.social

('planetearth.social',
 'planetearth.social',
 'Join planetearthsocial Show Your Love for Earth on a GeneralPurpose Mastodon Server',
 'Join planetearthsocial A Growing Community for Earth Lovers and Beyond Are you passionate about our beautiful planet and eager to connect with likeminded individuals who share your love for Mother Earth We invite you to be part of something special Welcome to planetearthsocial a new and blossoming Mastodon server dedicated to fostering sustainability environmental consciousness and diverse discussions As a new server we are excited to build a thriving community from the ground up and we need your unique voice to help us grow By joining planetearthsocial youll have the opportunity to shape the conversations forge new connections and make a meaningful impact within our closeknit community Heres why you should join us Be a Founding Member As an early adopter youll have the chance to be part of our servers foundation Share your ideas suggestions and interests as we shape the direction and culture of our growing community together Your voice truly matters Engage in Meaningful Discussions With a smaller closeknit community youll have a greater opportunity to engage in deeper and more personal conversations Share your thoughts on sustainability discover new perspectives and explore a wide range of topics that interest you Your contributions will be valued and appreciated Connect with LikeMinded Individuals By joining planetearthsocial youll connect with a group of passionate individuals who share your love for our planet Exchange ideas experiences and insights with fellow Earth enthusiasts who are just as eager as you to make a positive impact Forge lasting connections with likeminded souls Shape the Future Together Help us create a community that reflects our shared values and aspirations By actively participating and inviting others to join you contribute to the growth and vibrancy of planetearthsocial Together we can create a supportive and empowering space that inspires positive change Explore New Horizons As our community grows youll have the opportunity to discover diverse perspectives and engage in conversations that expand your knowledge and worldview From sustainability to various other interests the possibilities for exploration and learning are endless Join us at planetearthsocial today and be part of a vibrant and growing community that celebrates our planet and embraces a wide range of topics Together lets shape a future where sustainability and diverse discussions thrive We may be new but with your presence we can build something extraordinary Sign up now at planetearthsocial and be a part of our journey from the very beginning',
 '4.4.1',
 'https://github.com/mastodon/mastodon',
 56,
 ['Sexually explicit or violent media must be marked as sensitive when posting.',
  'No spam or advertising.',
  'No racism, sexism, homophobia, transphobia, xenophobia, or casteism.',
  'No incitement of violence or promotion of violent ideologies.',
  'No harassment, dogpiling or doxxing of other users.',
  'No illegal content.',
  'No spreading of fake news or misinformation.'])

In [12]:
# Split data into chunks
CHUNK_SIZE = 1000

def chunkify(data, size):
    for i in range(0, len(data), size):
        yield data[i:i+size]

In [13]:
# Parallelized execution
N_PROCESSES = 8
pool = Pool(N_PROCESSES)

# Results
results = []

# Chunks
chunks = list(chunkify(instances_list, CHUNK_SIZE))
print(f"Extracted {len(chunks)} chunks")

# Executing
for chunk in tqdm(chunks):
    pbar = tqdm(desc=f"Checking software",total=len(chunk))
    for res in pool.imap_unordered(get_instance_info, chunk):
        if res is not None:
            results.append(res)
        pbar.set_description(f"Checked(s): {len(results)} | Processed")
        pbar.update()
    pbar.close()

print("Instances checked: ", len(results))

Extracted 7 chunks

  0%|          | 0/7 [00:00<?, ?it/s]

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

pleroma.lord.re didn't declare any extended description!
Extended description found for leipzig.town
Error for instance: succubus.town
HTTPSConnectionPool(host='succubus.town', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4C560>: Failed to resolve 'succubus.town' ([Errno 11001] getaddrinfo failed)"))
Extended description found for v2br.social
Extended description found for social.bund.de
Extended description found for fosspri.de
Extended description found for mstdn.lt
Error for instance: social.hispabot.freemyip.com
HTTPSConnectionPool(host='social.hispabot.freemyip.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4CC50>: Failed to resolve 'social.hispabot.freemyip.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for indg.club
Extended description found for greennuclear.online
Extended description found for hoosier.social
Extended description found for toot.village.one
Extended description found for lifergeek.social
Error for instance: friendica.crazy-to-bike.de
HTTPSConnectionPool(host='friendica.crazy-to-bike.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'friendica.crazy-to-bike.de'. (_ssl.c:1000)")))
Extended description found for philately.social
Extended description found for gamedev.berlin
Extended description found for kzoo.to
pixelfed.scot didn't declare any extended description!
Extended description found for social.crablab.uk
Error for instance: posts.dumb.stuff.donaberger.xyz
HTTPSConnectionPool(host='posts.dumb.stuff.donaberger.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4E1E0>: Failed to resolve 'posts.dumb.stuff.donaberger.xyz' ([Errno 11001] getaddrinfo failed)"))
Extended description found for yharnam.singles
Extended description found for social.obeygravity.de
Extended description found for solarpunk.moe
Extended description found for greennet.social
Error for instance: hep.social
HTTPSConnectionPool(host='hep.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1A810>: Failed to resolve 'hep.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.webitel.me
Extended description found for social.jvns.ca
Extended description found for tooting.ninja
Error for instance: nicfab.it
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
Error for instance: nc.social
HTTPSConnectionPool(host='nc.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C86480>: Failed to resolve 'nc.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.sciences.re
Error for instance: hei.baby
HTTPSConnectionPool(host='hei.baby', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E231C54BC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Error for instance: friendicarg.nsupdate.info
HTTPSConnectionPool(host='friendicarg.nsupdate.info', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C562D0>: Failed to resolve 'friendicarg.nsupdate.info' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.macstories.net
Error for instance: iam.lydi.as
HTTPSConnectionPool(host='iam.lydi.as', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4C050>: Failed to resolve 'iam.lydi.as' ([Errno 11002] getaddrinfo failed)"))
Extended description found for reclaim.rocks
Error for instance: kemo.city
HTTPSConnectionPool(host='kemo.city', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A92240>: Failed to resolve 'kemo.city' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.rohangrey.net
HTTPSConnectionPool(host='social.rohangrey.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.rohangrey.net'. (_ssl.c:1000)")))
Extended description found for birdbutt.com
Error for instance: fedi.sabatino.pro
HTTPSConnectionPool(host='fedi.sabatino.pro', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4EEA0>: Failed to resolve 'fedi.sabatino.pro' ([Errno 11001] getaddrinfo failed)"))
Extended description found for m.epon.io
Extended description found for crab.garden
Extended description found for dagegenbewegen.social
Extended description found for strangeplace.me
Extended description found for social.tzi.fr
Error for instance: alternativos.pt
HTTPSConnectionPool(host='alternativos.pt', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for allpeep.social
Error for instance: social.diskseven.com
HTTPSConnectionPool(host='social.diskseven.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4DB20>: Failed to resolve 'social.diskseven.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for pon.ee
Extended description found for ecologie.social
Extended description found for tdd.social
Extended description found for grants.cafe
Error for instance: m.gretaoto.ca
HTTPSConnectionPool(host='m.gretaoto.ca', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4E900>: Failed to resolve 'm.gretaoto.ca' ([Errno 11001] getaddrinfo failed)"))
Error for instance: fd42.social
HTTPSConnectionPool(host='fd42.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4F800>: Failed to resolve 'fd42.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for jbo.socialExtended description found for mastodon.africa

Extended description found for games.ngo
Extended description found for recurse.social
Extended description found for social.asraelvudogel.de
Extended description found for m.aqr.af
Extended description found for livester.net
Error for instance: pleroma.pbb.lc
HTTPSConnectionPool(host='pleroma.pbb.lc', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A92660>: Failed to resolve 'pleroma.pbb.lc' ([Errno 11001] getaddrinfo failed)"))
Extended description found for attractive.space
Extended description found for graz.social
Extended description found for konfigurationsmanufaktur.de
Error for instance: social.tabletoptavern.online
HTTPSConnectionPool(host='social.tabletoptavern.online', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C86720>: Failed to resolve 'social.tabletoptavern.online' ([Errno 11001] getaddrinfo failed)"))
bolha.photos didn't declare any extended description!
Extended description found for mastodon.tuxtendo.nl
Extended description found for mas.to
Extended description found for muenchen.social
Extended description found for greatjustice.net
Extended description found for masto.nyc
Error for instance: connect.fshm.in
HTTPSConnectionPool(host='connect.fshm.in', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C54500>: Failed to resolve 'connect.fshm.in' ([Errno 11001] getaddrinfo failed)"))
Error for instance: olds.town
HTTPSConnectionPool(host='olds.town', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C87320>: Failed to resolve 'olds.town' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.la10cy.net
Error for instance: mastodon.lifebystills.co.uk
HTTPSConnectionPool(host='mastodon.lifebystills.co.uk', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C859A0>: Failed to resolve 'mastodon.lifebystills.co.uk' ([Errno 11002] getaddrinfo failed)"))
Error for instance: masto.epoch.dk
HTTPSConnectionPool(host='masto.epoch.dk', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C57440>: Failed to resolve 'masto.epoch.dk' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mstdn-jp.site
Error for instance: youthweb.social
HTTPSConnectionPool(host='youthweb.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C87CB0>: Failed to resolve 'youthweb.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for m6n.onsen.tech
Extended description found for toot.community
Extended description found for friendica.utzer.de
Error for instance: lounge.fan
HTTPSConnectionPool(host='lounge.fan', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C86720>: Failed to resolve 'lounge.fan' ([Errno 11001] getaddrinfo failed)"))
Error for instance: bcostodon.lol
HTTPSConnectionPool(host='bcostodon.lol', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAB110>: Failed to resolve 'bcostodon.lol' ([Errno 11001] getaddrinfo failed)"))
Extended description found for fedinerds.social
Extended description found for mathtod.online
Error for instance: insoumis-es.net
HTTPSConnectionPool(host='insoumis-es.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CA8050>: Failed to resolve 'insoumis-es.net' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.panic.com
Extended description found for s.pebcak.de
Extended description found for social.medlab.host
Extended description found for wptoots.social
Extended description found for mstdn.takuya-a.net
Extended description found for lor.sh
Extended description found for sauropods.win
Extended description found for social.easya.solutions
Extended description found for feistycricket.org
Extended description found for mastodon.wien
Extended description found for hueck.social
Error for instance: flr.social
HTTPSConnectionPool(host='flr.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAA0C0>: Failed to resolve 'flr.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for nejiamasi.com
Error for instance: sutrofan.com
HTTPSConnectionPool(host='www.sutrofan.com', port=443): Read timed out. (read timeout=10)
Extended description found for metalverse.social
Error for instance: mastodon.n41.lat
HTTPSConnectionPool(host='mastodon.n41.lat', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231C56DE0>, 'Connection to mastodon.n41.lat timed out. (connect timeout=19)'))
Extended description found for thelife.boats
Extended description found for m.nintendojo.fr
Error for instance: sotl.social
HTTPSConnectionPool(host='sotl.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: social.beaware.live
HTTPSConnectionPool(host='social.beaware.live', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B19A90>, 'Connection to social.beaware.live timed out. (connect timeout=19)'))
Error for instance: nulled.red
HTTPSConnectionPool(host='nulled.red', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: codeflow.club
Expecting value: line 1 column 1 (char 0)
Error for instance: mastodon.cluboftone.com
HTTPSConnectionPool(host='mastodon.cluboftone.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C54830>: Failed to resolve 'mastodon.cluboftone.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: fairdinkum.masto.host
HTTPSConnectionPool(host='fairdinkum.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.jesuislibre.net
Extended description found for breakpoint.cafe
Error for instance: cloud-native.social
HTTPSConnectionPool(host='cloud-native.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B4C8C0>, 'Connection to cloud-native.social timed out. (connect timeout=19)'))
Extended description found for nrkn.fr
Error for instance: sergal.org
Expecting value: line 1 column 1 (char 0)
Error for instance: me.memories.am
HTTPSConnectionPool(host='me.memories.am', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Extended description found for e.fo
Error for instance: bluelupine.social
HTTPSConnectionPool(host='bluelupine.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for furpark.kr
Extended description found for whisper.tf
Extended description found for isosceles.monster
Extended description found for m.ai6yr.org
Error for instance: sedryk.info
HTTPSConnectionPool(host='sedryk.info', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231C86AB0>, 'Connection to sedryk.info timed out. (connect timeout=19)'))
Extended description found for imd.social
Extended description found for legal.social
Extended description found for masto.alancfrancis.com
Error for instance: mastodon.retr0.party
HTTPSConnectionPool(host='mastodon.retr0.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for moe.cat
Error for instance: femdom.solutions
Expecting value: line 1 column 1 (char 0)
Extended description found for tsarolion.com
Extended description found for toot.wales
Error for instance: social.cluboftone.com
HTTPSConnectionPool(host='social.cluboftone.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4E300>: Failed to resolve 'social.cluboftone.com' ([Errno 11001] getaddrinfo failed)"))
pix.famichiki.jp didn't declare any extended description!
Error for instance: meow.zarchbox.fr
HTTPSConnectionPool(host='meow.zarchbox.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
Extended description found for hatchee.bz
Extended description found for social.horrorhub.club
Extended description found for rail.chat
Extended description found for toot.chez.gay
Extended description found for fedi.science
Extended description found for mastodon.dtalens.com
Error for instance: presidentissimo.com
HTTPSConnectionPool(host='presidentissimo.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4DAC0>: Failed to resolve 'presidentissimo.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: neomobius.com
HTTPSConnectionPool(host='neomobius.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.nikkasystems.com
Extended description found for mastodon.mx
Extended description found for pouet.space
Error for instance: talk.sevvie.ltd
HTTPSConnectionPool(host='talk.sevvie.ltd', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C56330>: Failed to resolve 'talk.sevvie.ltd' ([Errno 11001] getaddrinfo failed)"))
Extended description found for podcastindex.social
Extended description found for mastodon.dystroy.org
Error for instance: mastodon.geneticjen.com
HTTPSConnectionPool(host='mastodon.geneticjen.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4D1C0>: Failed to resolve 'mastodon.geneticjen.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: batorbros.me
Expecting value: line 1 column 1 (char 0)
Error for instance: vss365mast.org
HTTPSConnectionPool(host='vss365mast.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Error for instance: contrapointsfan.club
HTTPSConnectionPool(host='contrapointsfan.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C857F0>: Failed to resolve 'contrapointsfan.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for saptodon.org
Error for instance: trinitybristol.social

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

Error for instance: social.mpdl.mpg.de
HTTPSConnectionPool(host='social.mpdl.mpg.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324686E0>: Failed to resolve 'social.mpdl.mpg.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for hessen.social
Extended description found for ebooks.social
Extended description found for henshaw.social
Extended description found for pointless.chat
Error for instance: h5q.net
HTTPSConnectionPool(host='h5q.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232259A00>: Failed to resolve 'h5q.net' ([Errno 11001] getaddrinfo failed)"))
Extended description found for beamship.mpaq.org
Error for instance: social.cpluspatch.com
HTTPSConnectionPool(host='social.cpluspatch.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1C70>: Failed to resolve 'social.cpluspatch.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: okadon.masto.host
HTTPSConnectionPool(host='okadon.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for finfur.net
Error for instance: mastodon.rousset.nom.fr
HTTPSConnectionPool(host='mastodon.rousset.nom.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Extended description found for clacks.link
Error for instance: fluff.land
HTTPSConnectionPool(host='fluff.land', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for racoon.social
Extended description found for caleida.com
Error for instance: bgmastodon.com
HTTPSConnectionPool(host='bgmastodon.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1850>: Failed to resolve 'bgmastodon.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.heldscal.la
HTTPSConnectionPool(host='social.heldscal.la', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E232433980>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for monads.online
Extended description found for mastodon.hr
Error for instance: beerfactory.org
HTTPSConnectionPool(host='beerfactory.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324A8B90>: Failed to resolve 'beerfactory.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for retrogaming.social
Error for instance: orchard.social
HTTPSConnectionPool(host='orchard.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232259220>: Failed to resolve 'orchard.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for unvernunft.social
Error for instance: rosafluffmoln.nu
HTTPSConnectionPool(host='rosafluffmoln.nu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
Extended description found for w3c.social
Extended description found for mastodon-elestio-u1962.vm.elestio.app
Extended description found for mst.thumped.com
Error for instance: social.claes.se
HTTPSConnectionPool(host='social.claes.se', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1BB0>: Failed to resolve 'social.claes.se' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.llarian.net
HTTPSConnectionPool(host='mastodon.llarian.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1700>: Failed to resolve 'mastodon.llarian.net' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.thefword.club
HTTPSConnectionPool(host='mastodon.thefword.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4D7C0>: Failed to resolve 'mastodon.thefword.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for blabber.rocks
Error for instance: sinblr.com
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Extended description found for craftgoblin.club
Extended description found for yatil.social
Extended description found for catswords.social
Extended description found for sac.moe
Extended description found for lepoulsdumonde.com
Extended description found for mastodon.gamedev.place
Extended description found for ucb.social
Error for instance: gitmo.life
Expecting value: line 1 column 1 (char 0)
Extended description found for social.node001.net
Extended description found for social.kacens.dev
Extended description found for sfba.social
Extended description found for bark.lgbt
Extended description found for mastodon.bofhers.es
Extended description found for troet.social
Extended description found for bunny.social
Extended description found for tldr.nettime.org
Extended description found for procolix.social
Extended description found for telegrafverket.cc
Extended description found for river.group.lt
Extended description found for crosstalk.tech
Extended description found for fluffs.au
Error for instance: artalley.social
Expecting value: line 1 column 1 (char 0)
Extended description found for mastodon.thentrythis.org
Extended description found for kicou.info
Extended description found for mastodon.despise.computer
Extended description found for andeby.city
Extended description found for social.screamingatmyscreen.com
Extended description found for drosophila.social
spinster.xyz didn't declare any extended description!
Extended description found for www2.kt2003.info
Extended description found for ard.social
Extended description found for prlic.social
Error for instance: socialism.social
HTTPSConnectionPool(host='socialism.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E2321B2F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for wp-social.net
Extended description found for social.atypique.net
Extended description found for hacky.town
Extended description found for toot.igniterealtime.org
Error for instance: mastodon.host
HTTPSConnectionPool(host='mastodon.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for nightcord.de
Error for instance: antinetzwerk.de
HTTPSConnectionPool(host='antinetzwerk.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E6210>: Failed to resolve 'antinetzwerk.de' ([Errno 11002] getaddrinfo failed)"))
Error for instance: fedi.neufv.systems
HTTPSConnectionPool(host='fedi.neufv.systems', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232258890>: Failed to resolve 'fedi.neufv.systems' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.rocks
HTTPSConnectionPool(host='mastodon.rocks', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23225B440>: Failed to resolve 'mastodon.rocks' ([Errno 11002] getaddrinfo failed)"))
Extended description found for quokka.city
Extended description found for mastodon.li
Extended description found for joshbutts.social
Extended description found for bangdream.space
Extended description found for chin-co-ne.co
Extended description found for tivia.social
Extended description found for gabvp.masto.host
Extended description found for social.nah.re
Extended description found for mutual.tls.zone
Extended description found for polsci.social
Error for instance: hostux.eu
HTTPSConnectionPool(host='hostux.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'hostux.eu'. (_ssl.c:1000)")))
Error for instance: nutt.church
HTTPSConnectionPool(host='nutt.church', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2324327E0>, 'Connection to nutt.church timed out. (connect timeout=19)'))
Extended description found for elonsucks.org
Error for instance: social.romeov.me
HTTPSConnectionPool(host='social.romeov.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23218B560>: Failed to resolve 'social.romeov.me' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.so.football
HTTPSConnectionPool(host='mastodon.so.football', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2323C15E0>, 'Connection to mastodon.so.football timed out. (connect timeout=19)'))
Extended description found for ijug.social
Extended description found for our.devchatter.com
Extended description found for farmgarden.nora.social
Error for instance: religion.masto.host
HTTPSConnectionPool(host='religion.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: mastodon.my
HTTPSConnectionPool(host='social.mastodon.my', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324A84A0>: Failed to resolve 'social.mastodon.my' ([Errno 11002] getaddrinfo failed)"))
Error for instance: spectreofcommunism.boo
HTTPSConnectionPool(host='spectreofcommunism.boo', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'spectreofcommunism.boo'. (_ssl.c:1000)")))
Extended description found for acg.mn
Extended description found for mastodon.sl
Extended description found for calamity.world
Error for instance: leafposter.club
HTTPSConnectionPool(host='leafposter.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324A8860>: Failed to resolve 'leafposter.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for gamingjp.org
Error for instance: nobigtech.es
HTTPSConnectionPool(host='www.nobigtech.es', port=443): Read timed out. (read timeout=10)
Error for instance: restraint.social
HTTPSConnectionPool(host='restraint.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
Error for instance: m.wolfwater.com
HTTPSConnectionPool(host='m.wolfwater.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B1AC90>, 'Connection to m.wolfwater.com timed out. (connect timeout=19)'))
Error for instance: social.ataxya.net
HTTPSConnectionPool(host='social.ataxya.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.ataxya.net'. (_ssl.c:1000)")))
Error for instance: sns.azkware.net
HTTPSConnectionPool(host='sns.azkware.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Extended description found for freiewaehler.social
Extended description found for kvlt.zone
Extended description found for religious.social
faf.social didn't declare any extended description!
Error for instance: mizzkey.zapto.org
HTTPSConnectionPool(host='mizzkey.zapto.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23225A360>: Failed to resolve 'mizzkey.zapto.org' ([Errno 11001] getaddrinfo failed)"))
Error for instance: cyberpunk.earth
Expecting value: line 1 column 1 (char 0)
Extended description found for m.rakyll.org
Error for instance: social.pbb.lc
HTTPSConnectionPool(host='social.pbb.lc', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23225B290>: Failed to resolve 'social.pbb.lc' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodos.com
Error for instance: wndp.cloud
HTTPSConnectionPool(host='wndp.cloud', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for newsmast.community
Extended description found for otadon.com
Extended description found for mastodon.omnigroup.com
Extended description found for sphere.fx4.net
Extended description found for a2mi.social
Error for instance: umisskey.com
HTTPSConnectionPool(host='umisskey.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232188FB0>: Failed to resolve 'umisskey.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for simon.vreeman.com
Extended description found for wstrsd.masto.host
Extended description found for kampftoast.de
Extended description found for toot.funnylookinhat.com
Error for instance: gred.al
HTTPSConnectionPool(host='gred.al', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2322586E0>: Failed to resolve 'gred.al' ([Errno 11001] getaddrinfo failed)"))
Extended description found for planet.moe
Extended description found for pouet.it
Extended description found for abpe.org
Extended description found for joomla.social
Extended description found for friendhole.social
Extended description found for zhub.link
Error for instance: mstdn.mobilehackerz.jp
HTTPSConnectionPool(host='mstdn.mobilehackerz.jp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324DB200>: Failed to resolve 'mstdn.mobilehackerz.jp' ([Errno 11001] getaddrinfo failed)"))
Extended description found for io.mwl.io
Error for instance: catgram.jp
HTTPSConnectionPool(host='catgram.jp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23225A360>: Failed to resolve 'catgram.jp' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.moule.world
Extended description found for digforfire.org
Extended description found for mieth.social
Error for instance: mastodon.cooleysekula.net
HTTPSConnectionPool(host='mastodon.cooleysekula.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2321B1A90>, 'Connection to mastodon.cooleysekula.net timed out. (connect timeout=19)'))
Error for instance: fedi.bapril.pl
HTTPSConnectionPool(host='fedi.bapril.pl', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for mastodon.opportunis.me
Error for instance: philipjohn.social
HTTPSConnectionPool(host='philipjohn.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for letallmortalfleshfindtheirvoice.social
Error for instance: aus.community
HTTPSConnectionPool(host='aus.community', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232468920>: Failed to resolve 'aus.community' ([Errno 11001] getaddrinfo failed)"))
Error for instance: fimidi.com
HTTPSConnectionPool(host='fimidi.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
Extended description found for oisaur.com
Extended description found for moresci.sale
Extended description found for tams.tech
Extended description found for wehavecookies.social
Error for instance: say.berk.es
HTTPSConnectionPool(host='say.berk.es', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E23225B9E0>, 'Connection to say.berk.es timed out. (connect timeout=19)'))
Extended description found for dnsimple.social
Error for instance: lost-in-outer.space
HTTPSConnectionPool(host='lost-in-outer.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for notacult.social
Error for instance: werebeast.net
HTTPSConnectionPool(host='werebeast.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Extended description found for digitalcourage.social
pleroma.soykaf.com didn't declare any extended description!
Extended description found for share.elouworld.org
Error for instance: dt.gl
HTTPSConnectionPool(host='dt.gl', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.avery.cafe

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

Error for instance: arthaus.social
HTTPSConnectionPool(host='arthaus.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E4AA0>: Failed to resolve 'arthaus.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.tobedefined.net
HTTPSConnectionPool(host='mastodon.tobedefined.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Error for instance: mastodon.preppers-shelter.nl
HTTPSConnectionPool(host='mastodon.preppers-shelter.nl', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mastodon.preppers-shelter.nl'. (_ssl.c:1000)")))
Extended description found for fedi.cyberwitches.club
Extended description found for nerdculture.de
Error for instance: masto.posweg.es
HTTPSConnectionPool(host='masto.posweg.es', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B183B0>: Failed to resolve 'masto.posweg.es' ([Errno 11001] getaddrinfo failed)"))
Error for instance: ding.so
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Extended description found for miau.le-chat-a-velo.at
Extended description found for skyjake.fi
Extended description found for troet.burg-halle.de
Extended description found for icanteventoot.help
Error for instance: sharkey.tombies.eu
HTTPSConnectionPool(host='sharkey.tombies.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1AC00>: Failed to resolve 'sharkey.tombies.eu' ([Errno 11001] getaddrinfo failed)"))
Extended description found for skeptics.social
Extended description found for mamutovo.cz
Extended description found for social.oaf.org.au
Error for instance: social.amatriain.site
HTTPSConnectionPool(host='social.amatriain.site', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A75EB0>: Failed to resolve 'social.amatriain.site' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.tumelum.de
Extended description found for masto.deoan.org
Extended description found for masto.asonix.dog
Error for instance: suedi.club
HTTPSConnectionPool(host='suedi.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'suedi.club'. (_ssl.c:1000)")))
Error for instance: explosion.party
HTTPSConnectionPool(host='explosion.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E231B01880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for mastodon.cipherbliss.com
Extended description found for krigskunst.social
Extended description found for social.brainsys.com
Extended description found for monsterfuckers.online
Error for instance: aztlansocial.site
HTTPSConnectionPool(host='aztlansocial.site', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1B620>: Failed to resolve 'aztlansocial.site' ([Errno 11001] getaddrinfo failed)"))
Extended description found for secluded.ch
Extended description found for persadon.com
Error for instance: wao.wtf
HTTPSConnectionPool(host='wao.wtf', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAAED0>: Failed to resolve 'wao.wtf' ([Errno 11001] getaddrinfo failed)"))
Error for instance: vrsocial.network
HTTPSConnectionPool(host='vrsocial.network', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232393B30>: Failed to resolve 'vrsocial.network' ([Errno 11001] getaddrinfo failed)"))
Extended description found for masto.ai
Extended description found for alvarado.social
Extended description found for information.garden
Extended description found for apricot.social
Extended description found for vixen.zone
Extended description found for mastodon.ameo.dev
Extended description found for thehappyfamily.stream
Error for instance: angrydome.au
HTTPSConnectionPool(host='angrydome.au', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A76A20>: Failed to resolve 'angrydome.au' ([Errno 11002] getaddrinfo failed)"))
Error for instance: nonsocialand.space
HTTPSConnectionPool(host='nonsocialand.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E6810>: Failed to resolve 'nonsocialand.space' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.ftm.nl
Error for instance: status.homecomputing.fr
HTTPSConnectionPool(host='status.homecomputing.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'status.homecomputing.fr'. (_ssl.c:1000)")))
Extended description found for toot.vipra.vip
Error for instance: exploit.social
HTTPSConnectionPool(host='exploit.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CA9370>: Failed to resolve 'exploit.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.si
Extended description found for mostodon.de
Error for instance: guillotines.masto.host
HTTPSConnectionPool(host='guillotines.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: dartboard.social
HTTPSConnectionPool(host='dartboard.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232390440>: Failed to resolve 'dartboard.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for krefeld.life
Extended description found for write.echoless.space
Error for instance: asteroidm.space
HTTPSConnectionPool(host='asteroidm.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B18710>: Failed to resolve 'asteroidm.space' ([Errno 11001] getaddrinfo failed)"))
Error for instance: benedikts.social
HTTPSConnectionPool(host='benedikts.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23225B740>: Failed to resolve 'benedikts.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: cybre.town
HTTPSConnectionPool(host='cybre.town', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for lincolnite.net
Error for instance: me.oer.me
HTTPSConnectionPool(host='me.oer.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
Extended description found for poorlyrendered.com
Extended description found for taiwan.wtf
Extended description found for cville.online
Error for instance: bibletalk.social
Expecting value: line 1 column 1 (char 0)
Error for instance: dragons.masto.host
HTTPSConnectionPool(host='dragons.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: social.defluence.me
HTTPSConnectionPool(host='social.defluence.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1BAD0>: Failed to resolve 'social.defluence.me' ([Errno 11001] getaddrinfo failed)"))
Error for instance: cmx.im
Expecting value: line 1 column 1 (char 0)
Error for instance: nottyboi.me
HTTPSConnectionPool(host='nottyboi.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B18290>: Failed to resolve 'nottyboi.me' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.sp-codes.de
Error for instance: pleroma.cloud
HTTPSConnectionPool(host='pleroma.cloud', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B19FA0>: Failed to resolve 'pleroma.cloud' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.r-flash.eu
Error for instance: social.ahlcode.fi
HTTPSConnectionPool(host='social.ahlcode.fi', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1A570>: Failed to resolve 'social.ahlcode.fi' ([Errno 11001] getaddrinfo failed)"))
Extended description found for kommentakerfid.is
Error for instance: lit.tlespace.xyz
Expecting value: line 1 column 1 (char 0)
Error for instance: micro.hcj.sh
HTTPSConnectionPool(host='micro.hcj.sh', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2322594C0>: Failed to resolve 'micro.hcj.sh' ([Errno 11001] getaddrinfo failed)"))
Extended description found for phire.place
Error for instance: mastodon.technology
HTTPSConnectionPool(host='mastodon.technology', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4CAA0>: Failed to resolve 'mastodon.technology' ([Errno 11001] getaddrinfo failed)"))
Extended description found for meow.cloud
Error for instance: m.beautifullosers.org
HTTPSConnectionPool(host='m.beautifullosers.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D321E0>: Failed to resolve 'm.beautifullosers.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for aleph.land
Extended description found for lou.lt
Extended description found for glasgow.social
Error for instance: owata.m.to
HTTPSConnectionPool(host='owata.m.to', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A749E0>: Failed to resolve 'owata.m.to' ([Errno 11001] getaddrinfo failed)"))
Extended description found for linuxrocks.online
Extended description found for toot.cafe
Extended description found for energydon.fi
Error for instance: moonbeam.dance
HTTPSConnectionPool(host='moonbeam.dance', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CABAA0>: Failed to resolve 'moonbeam.dance' ([Errno 11001] getaddrinfo failed)"))
Extended description found for skastodon.com
Extended description found for tulipgardenshow.masto.host
Extended description found for mastodon.blaede.family
Extended description found for pocketpixels.club
Extended description found for jit.social
Error for instance: handlewalks.masto.host
HTTPSConnectionPool(host='handlewalks.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for miserables.net
Extended description found for synapse.cafe
Error for instance: digitalmarketer.social
HTTPSConnectionPool(host='digitalmarketer.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E5640>: Failed to resolve 'digitalmarketer.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for ingenthron.social
Extended description found for linguisten.info
Error for instance: b0x.social
Exceeded 30 redirects.
Extended description found for social.tr0llhoehle.de
Error for instance: socia.esperant.io
HTTPSConnectionPool(host='socia.esperant.io', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232258BF0>: Failed to resolve 'socia.esperant.io' ([Errno 11001] getaddrinfo failed)"))
Extended description found for pagan.plus
Extended description found for vocalodon.net
Extended description found for discuss.systems
Extended description found for nofun.social
Error for instance: m.sclo.nl
HTTPSConnectionPool(host='m.sclo.nl', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B419A0>: Failed to resolve 'm.sclo.nl' ([Errno 11001] getaddrinfo failed)"))
Extended description found for thepit.social
Error for instance: plamo.social
HTTPSConnectionPool(host='plamo.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A76900>: Failed to resolve 'plamo.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for linuxlab.sh
Extended description found for romancelandia.club
Extended description found for pipou.academy
Extended description found for endtimebelievers.com
Extended description found for uuu.moe
digitalcourage.photo didn't declare any extended description!
Extended description found for mastodon.canonicity.org
Extended description found for expressional.social
Extended description found for moo.nz
Extended description found for pynews.com.br
Error for instance: mookiesplace.com
HTTPSConnectionPool(host='mookiesplace.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C86900>: Failed to resolve 'mookiesplace.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: anime.website
HTTPSConnectionPool(host='anime.website', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324C66F0>: Failed to resolve 'anime.website' ([Errno 11001] getaddrinfo failed)"))
Extended description found for friends.ravergram.club
Extended description found for h-net.social
Error for instance: lush.moe
HTTPSConnectionPool(host='lush.moe', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B199D0>: Failed to resolve 'lush.moe' ([Errno 11001] getaddrinfo failed)"))
Error for instance: ap.kios.cc
HTTPSConnectionPool(host='ap.kios.cc', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232391190>: Failed to resolve 'ap.kios.cc' ([Errno 11001] getaddrinfo failed)"))
Extended description found for 1uca.com
Error for instance: mastodon.ellouisdocker.synology.me
HTTPSConnectionPool(host='mastodon.ellouisdocker.synology.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B02E70>: Failed to resolve 'mastodon.ellouisdocker.synology.me' ([Errno 11001] getaddrinfo failed)"))
Extended description found for imastodon.org
Extended description found for androiddev.social
Extended description found for odakyu.app
Extended description found for mastodon.laurakalbag.com
Extended description found for diaspodon.fr
Error for instance: themuscle.farm
HTTPSConnectionPool(host='themuscle.farm', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E6A80>: Failed to resolve 'themuscle.farm' ([Errno 11001] getaddrinfo failed)"))
Extended description found for is-a.cat
Extended description found for ukrainian.network
Extended description found for cityofchicago.live
Error for instance: mastodonindonesia.com
HTTPSConnectionPool(host='mastodonindonesia.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E67E0>: Failed to resolve 'mastodonindonesia.com' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.chotto.moe
HTTPSConnectionPool(host='mastodon.chotto.moe', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232391400>: Failed to resolve 'mastodon.chotto.moe' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.bawue.social
Extended description found for dorset.social
Extended description found for noodle.social
Extended description found for mastodon.teia.art
Error for instance: micro.baixllobregat.social
Expecting value: line 1 column 1 (char 0)
Extended description found for cubhub.social
Extended description found for mastodon.chrisduffley.com
Extended description found for quarteredcircle.net
Extended description found for mstdn.hokkaido.jp
Extended description found for gensokyo.social
Error for instance: jtworld.xyz
HTTPSConnectionPool(host='jtworld.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'jtworld.xyz'. (_ssl.c:1000)")))
Error for instance: fedi.getimiskon.xyz
HTTPSConnectionPool(host='fedi.getimiskon.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'fedi.getimiskon.xyz'. (_ssl.c:1000)")))
Extended description found for posthat.ca
Extended description found for bookstodon.thestorygraph.com
Extended description found for barcamp.social
Extended description found for front-end.social
Extended description found for social.schaffenburg.org
pleroma.microblog.se didn't declare any extended description!
Extended description found for mastodon.la
Extended description found for historians.social
Extended description found for 1password.social
Extended description found for mastodon.green
Error for instance: social.jpa.com

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

Error for instance: r18.social
HTTPSConnectionPool(host='r18.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAA600>: Failed to resolve 'r18.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mieke.club
HTTPSConnectionPool(host='mieke.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1BDD0>: Failed to resolve 'mieke.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for progressivecafe.social
Extended description found for scholar.social
Extended description found for gulp.cafe
Extended description found for mastodon.derg.nz
Extended description found for frankwiles.social
Extended description found for tiphon.nerv-project.eu
Extended description found for social.coop
Extended description found for fedifreu.de
Error for instance: hub.cayra.info
HTTPSConnectionPool(host='hub.cayra.info', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Extended description found for rheinneckar.social
Extended description found for mastodon.hawaga.org.uk
Error for instance: mastodon.comorichico.com
HTTPSConnectionPool(host='mastodon.comorichico.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A75640>: Failed to resolve 'mastodon.comorichico.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for activitypub.garmy.jp
Error for instance: social.safestreetrebel.com
HTTPSConnectionPool(host='social.safestreetrebel.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B41430>: Failed to resolve 'social.safestreetrebel.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for marctodon.marci.one
Extended description found for howdee.social
Error for instance: fedi.vdheide.net
HTTPSConnectionPool(host='fedi.vdheide.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D33D10>: Failed to resolve 'fedi.vdheide.net' ([Errno 11001] getaddrinfo failed)"))
Error for instance: m.toad.host
HTTPSConnectionPool(host='m.toad.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B002F0>: Failed to resolve 'm.toad.host' ([Errno 11002] getaddrinfo failed)"))
Extended description found for changelog.social
Error for instance: eeee.no
HTTPSConnectionPool(host='eeee.no', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
miniwa.moe didn't declare any extended description!
Extended description found for mastodon.wellperns.com
Error for instance: mastodon.teachmaths.org
HTTPSConnectionPool(host='mastodon.teachmaths.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D33200>: Failed to resolve 'mastodon.teachmaths.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mstdn-amadeus.tech
Extended description found for leftist.network
Error for instance: uwu.st
HTTPSConnectionPool(host='uwu.st', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'uwu.st'. (_ssl.c:1000)")))
Error for instance: community-patriots.social
HTTPSConnectionPool(host='community-patriots.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A92F60>: Failed to resolve 'community-patriots.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for sakh.social
Extended description found for mastodon.tn
Error for instance: cryptodon.lol
HTTPSConnectionPool(host='cryptodon.lol', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for fedi.lynnesbian.space
Extended description found for clockwork.monster
Error for instance: nafo.army
HTTPSConnectionPool(host='nafo.army', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'nafo.army'. (_ssl.c:1000)")))
Error for instance: fedi.sabatino.cloud
HTTPSConnectionPool(host='fedi.sabatino.cloud', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
Error for instance: phreedom.tk
HTTPSConnectionPool(host='phreedom.tk', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232550D40>: Failed to resolve 'phreedom.tk' ([Errno 11001] getaddrinfo failed)"))
Error for instance: norwoodzero.net
HTTPSConnectionPool(host='norwoodzero.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2322586E0>: Failed to resolve 'norwoodzero.net' ([Errno 11001] getaddrinfo failed)"))
Error for instance: dvlup.social
HTTPSConnectionPool(host='dvlup.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for mstdn.anchel.nl
Extended description found for nojack.easydns.ca
Extended description found for masto.es
Error for instance: music.pawoo.net
HTTPSConnectionPool(host='music.pawoo.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))
Error for instance: mamout.xyz
HTTPSConnectionPool(host='mamout.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.gnuweeb.org
Error for instance: mastodon.saatanantunar.it
HTTPSConnectionPool(host='mastodon.saatanantunar.it', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for follow.ethanmarcotte.com
Extended description found for woof.group
Extended description found for jorts.horse
Extended description found for social.rights.ninja
Extended description found for tutoteket.no
Extended description found for higheredweb.social
Error for instance: brrrt.eu
HTTPSConnectionPool(host='brrrt.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232550BF0>: Failed to resolve 'brrrt.eu' ([Errno 11001] getaddrinfo failed)"))
Extended description found for sick.social
Extended description found for recordplug.club
Extended description found for social.veraciousnetwork.com
Error for instance: social.curta.red
HTTPSConnectionPool(host='social.curta.red', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D30BC0>: Failed to resolve 'social.curta.red' ([Errno 11001] getaddrinfo failed)"))
Extended description found for noxon.cc
Extended description found for mastodon.energy
Extended description found for social.veltens.org
Extended description found for ajtaci.club
Extended description found for mstdn.nursing.unibas.ch
Error for instance: masto.mkm.scot
HTTPSConnectionPool(host='masto.mkm.scot', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B40890>: Failed to resolve 'masto.mkm.scot' ([Errno 11001] getaddrinfo failed)"))
Extended description found for lsbt.me
Extended description found for social.yewdar.world
Extended description found for genista.osrx.chat
Extended description found for mastodon.missing-deadlines.com
Error for instance: fox.gal
HTTPSConnectionPool(host='fox.gal', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1AC60>: Failed to resolve 'fox.gal' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.lgbt
Extended description found for social.process-one.net
Error for instance: shonk.social
HTTPSConnectionPool(host='shonk.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1000)')))
Extended description found for isfeeling.social
Extended description found for bologna.one
Extended description found for nonbiridon.hostdon.ne.jp
Extended description found for go5.dev
Extended description found for masto.onurb.net
Extended description found for post.lurk.org
Extended description found for social.raytec.co
Error for instance: cogley.jp
HTTPSConnectionPool(host='cogley.jp', port=443): Read timed out. (read timeout=10)
Extended description found for spacehost.team
Extended description found for mastodon.constant.social
Extended description found for wetdry.world
planetrage.social didn't declare any extended description!
Extended description found for mastodon.grants.cafe
Extended description found for status.kinlan.me
Error for instance: brokenmirror.cc
HTTPSConnectionPool(host='brokenmirror.cc', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324D9880>: Failed to resolve 'brokenmirror.cc' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mstdn.health
HTTPSConnectionPool(host='mstdn.health', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D030E0>: Failed to resolve 'mstdn.health' ([Errno 11001] getaddrinfo failed)"))
Extended description found for milliways.social
Extended description found for gulo.monster
Error for instance: ipv6.camp
HTTPSConnectionPool(host='ipv6.camp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323E74D0>: Failed to resolve 'ipv6.camp' ([Errno 11001] getaddrinfo failed)"))
Extended description found for degrowth.social
Extended description found for configure.ac
Extended description found for fuzzytacular.net
Error for instance: s.knusper-land.de
HTTPSConnectionPool(host='s.knusper-land.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for sms.cybik.moe
Error for instance: tuiter.ga
HTTPSConnectionPool(host='tuiter.ga', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D315B0>: Failed to resolve 'tuiter.ga' ([Errno 11001] getaddrinfo failed)"))
Extended description found for masto.p-nintendo.com
Extended description found for gensokyo.town
lolison.top didn't declare any extended description!
Extended description found for social.python.it
Extended description found for cailincat.cloud
Extended description found for foxes.rocks
Error for instance: occult.camp
HTTPSConnectionPool(host='occult.camp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1BCB0>: Failed to resolve 'occult.camp' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.stopwatchingus-heidelberg.de
HTTPSConnectionPool(host='social.stopwatchingus-heidelberg.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.stopwatchingus-heidelberg.de'. (_ssl.c:1000)")))
Extended description found for mastodon.lwr.wtf
Error for instance: dhub.social
HTTPSConnectionPool(host='dhub.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: social.peregrinecoast.press
HTTPSConnectionPool(host='social.peregrinecoast.press', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E231B4D4F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for chabant.social
Extended description found for rda.komintern.work
Extended description found for edi.social
Extended description found for social.praxis.nyc
Error for instance: jiro.m.to
HTTPSConnectionPool(host='jiro.m.to', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323C1DF0>: Failed to resolve 'jiro.m.to' ([Errno 11001] getaddrinfo failed)"))
Error for instance: globalfrens.com
HTTPSConnectionPool(host='globalfrens.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246BDA0>: Failed to resolve 'globalfrens.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for haunt.graveyard.boo
Extended description found for sculpin.social
Error for instance: malmo.chat
HTTPSConnectionPool(host='malmo.chat', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246AD50>: Failed to resolve 'malmo.chat' ([Errno 11001] getaddrinfo failed)"))
Extended description found for rails.social
Error for instance: hostux.coffee
HTTPSConnectionPool(host='hostux.coffee', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324692B0>: Failed to resolve 'hostux.coffee' ([Errno 11001] getaddrinfo failed)"))
Extended description found for blogi.social
Error for instance: cliq.social
HTTPSConnectionPool(host='cliq.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231A74DD0>, 'Connection to cliq.social timed out. (connect timeout=19)'))
Error for instance: staysilent.party
HTTPSConnectionPool(host='staysilent.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232259100>, 'Connection to staysilent.party timed out. (connect timeout=19)'))
Extended description found for homestead.social
Extended description found for curmudgeon.cafe
Error for instance: chowchow.social
HTTPSConnectionPool(host='chowchow.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246B230>: Failed to resolve 'chowchow.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: ruzik.xyz
Expecting value: line 1 column 1 (char 0)
Extended description found for opencoaster.net
Error for instance: mastodon.hasameli.com
HTTPSConnectionPool(host='mastodon.hasameli.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mastodon.hasameli.com'. (_ssl.c:1000)")))
Extended description found for social.penguinability.net
Extended description found for social.pupsplus.fans
Extended description found for kotobaphil-mtdn.eu
Error for instance: neovibe.app
HTTPSConnectionPool(host='neovibe.app', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4D190>: Failed to resolve 'neovibe.app' ([Errno 11002] getaddrinfo failed)"))
Extended description found for mst.ramsdr.ru
Error for instance: rainy.pizza
HTTPSConnectionPool(host='rainy.pizza', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B424E0>: Failed to resolve 'rainy.pizza' ([Errno 11001] getaddrinfo failed)"))
Extended description found for adney.land
Error for instance: p.talesbythewanderer.com
HTTPSConnectionPool(host='p.talesbythewanderer.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E23246B590>, 'Connection to p.talesbythewanderer.com timed out. (connect timeout=19)'))
Error for instance: lazy8.social
HTTPSConnectionPool(host='lazy8.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAA9C0>: Failed to resolve 'lazy8.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mstdn.cuezakuisgodofthe.world
HTTPSConnectionPool(host='mstdn.cuezakuisgodofthe.world', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B18230>: Failed to resolve 'mstdn.cuezakuisgodofthe.world' ([Errno 11001] getaddrinfo failed)"))
Error for instance: troete.ztrl.de
HTTPSConnectionPool(host='troete.ztrl.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4E930>: Failed to resolve 'troete.ztrl.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.content.town
Extended description found for hex.st
Extended description found for reidodon.net
Error for instance: hackers.town
HTTPSConnectionPool(host='hackers.town', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2324D87A0>, 'Connection to hackers.town timed out. (connect timeout=19)'))
Extended description found for idlethumbs.social
Extended description found for mastodon.zaclys.com
Extended description found for scorpinc.social
Extended description found for blob.love
Extended description found for toots.sahilister.in
Extended description found for mstdn.klamath.jp
Error for instance: akkoma.cryptoschizo.club

C:\Users\alelc\AppData\Local\Temp\ipykernel_28188\2336991912.py:6: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a URL than HTML or XML.

If you meant to use Beautiful Soup to parse the web page found at a certain URL, then something has gone wrong. You should use an Python package like 'requests' to fetch the content behind the URL. Once you have the content as a string, you can feed that string into Beautiful Soup.

However, if you want to parse some data that happens to look like a URL, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  soup = BeautifulSoup(text, "html.parser")

Extended description found for loma.ml
Extended description found for varmint.town
Error for instance: alphaville.club
HTTPSConnectionPool(host='alphaville.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C55700>: Failed to resolve 'alphaville.club' ([Errno 11001] getaddrinfo failed)"))
Error for instance: varishangout.net
'rules'
Error for instance: freak.university
HTTPSConnectionPool(host='freak.university', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232552570>: Failed to resolve 'freak.university' ([Errno 11001] getaddrinfo failed)"))
Error for instance: pleroma.noellabo.jp
HTTPSConnectionPool(host='pleroma.noellabo.jp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232550C80>, 'Connection to pleroma.noellabo.jp timed out. (connect timeout=19)'))
Extended description found for yeg.bike
Error for instance: erotic.social
HTTPSConnectionPool(host='erotic.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D02930>: Failed to resolve 'erotic.social' ([Errno 11002] getaddrinfo failed)"))
Extended description found for claristdon.link
Extended description found for fasol.org
Extended description found for mediapart.social
Extended description found for nsinteger.com
Error for instance: nuvem.lgbt
Expecting value: line 1 column 1 (char 0)
Error for instance: mastodon.roitsystems.ca
HTTPSConnectionPool(host='mastodon.roitsystems.ca', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2321B2720>, 'Connection to mastodon.roitsystems.ca timed out. (connect timeout=19)'))
Error for instance: pl.murky.club
HTTPSConnectionPool(host='pl.murky.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D014F0>: Failed to resolve 'pl.murky.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for superhappy.social
Extended description found for social.openhood.ru
Error for instance: social.bitcast.info
HTTPSConnectionPool(host='social.bitcast.info', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324DA3F0>: Failed to resolve 'social.bitcast.info' ([Errno 11001] getaddrinfo failed)"))
Extended description found for juju.house
Extended description found for toot.melonland.net
Extended description found for social.cu2d.com
Extended description found for deepthot.org
Extended description found for toot.garden
Error for instance: myfedi.de
HTTPSConnectionPool(host='myfedi.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D31F70>: Failed to resolve 'myfedi.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for utter.online
Extended description found for social.bitfolk.com
Extended description found for social.illusory.ink
Extended description found for mastodon.1984.cz
Extended description found for karlsruhe-social.de
Error for instance: mstdn.id
Expecting value: line 1 column 1 (char 0)
Extended description found for pub.communistparty.org.uk
Extended description found for mastobate.social
Error for instance: animal.church
HTTPSConnectionPool(host='animal.church', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
social.itm.osaka didn't declare any extended description!
jir.moe didn't declare any extended description!
Error for instance: social.spectreos.de
HTTPSConnectionPool(host='social.spectreos.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246BCE0>: Failed to resolve 'social.spectreos.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mstdn.ima1zumi.com
Extended description found for hal9.ooo
Error for instance: charlestown.social
HTTPSConnectionPool(host='charlestown.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232551850>, 'Connection to charlestown.social timed out. (connect timeout=19)'))
Error for instance: social.notmyidea.org
HTTPSConnectionPool(host='social.notmyidea.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B437D0>: Failed to resolve 'social.notmyidea.org' ([Errno 11001] getaddrinfo failed)"))
Error for instance: toot.feynman.monster
HTTPSConnectionPool(host='toot.feynman.monster', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232259100>: Failed to resolve 'toot.feynman.monster' ([Errno 11001] getaddrinfo failed)"))
Extended description found for saskodon.ca
Extended description found for mato.social
Extended description found for amicale.net
Extended description found for edamame.social
Error for instance: mastodon.horde.net.br
HTTPSConnectionPool(host='mastodon.horde.net.br', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B40320>: Failed to resolve 'mastodon.horde.net.br' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.hostdon.ne.jp
Extended description found for d20.social
Extended description found for wybt.net
Extended description found for thecanadian.social
Error for instance: pl.wizards.zone
HTTPSConnectionPool(host='pl.wizards.zone', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323C0B00>: Failed to resolve 'pl.wizards.zone' ([Errno 11001] getaddrinfo failed)"))
Error for instance: the.hedgehoghunter.club
HTTPSConnectionPool(host='the.hedgehoghunter.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B3B60>: Failed to resolve 'the.hedgehoghunter.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for pigeons.club
Extended description found for rage.love
Extended description found for pravda.me
Error for instance: chico.moe
HTTPSConnectionPool(host='chico.moe', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324DA4E0>: Failed to resolve 'chico.moe' ([Errno 11001] getaddrinfo failed)"))
Extended description found for brands.town
Extended description found for weserbergland.social
Extended description found for spacey.space
Extended description found for social.lfx.dev
Extended description found for vrparty.social
Error for instance: social.hayalmasal.org
HTTPSConnectionPool(host='social.hayalmasal.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D038F0>: Failed to resolve 'social.hayalmasal.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for wandzeitung.xyz
Error for instance: screenwriting.space
HTTPSConnectionPool(host='screenwriting.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D031A0>: Failed to resolve 'screenwriting.space' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.ninja
HTTPSConnectionPool(host='mastodon.ninja', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246BC20>: Failed to resolve 'mastodon.ninja' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.wiuwiu.de
HTTPSConnectionPool(host='social.wiuwiu.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232430EC0>: Failed to resolve 'social.wiuwiu.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.business
Extended description found for netzkms.de
pleroma.debian.social didn't declare any extended description!
Extended description found for goettingen.social
Extended description found for social.anaproy.nl
Extended description found for rah.social
Extended description found for hamradio.tel
Extended description found for mazaska.social
Extended description found for social.masked.cloud
Error for instance: exile.social
HTTPSConnectionPool(host='exile.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B401D0>, 'Connection to exile.social timed out. (connect timeout=19)'))
Error for instance: gs.smuglo.li
HTTPSConnectionPool(host='gs.smuglo.li', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232430410>: Failed to resolve 'gs.smuglo.li' ([Errno 11001] getaddrinfo failed)"))
Extended description found for glammr.us
Error for instance: fd8oz4oesnvit.hopto.org
HTTPSConnectionPool(host='fd8oz4oesnvit.hopto.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324302C0>: Failed to resolve 'fd8oz4oesnvit.hopto.org' ([Errno 11001] getaddrinfo failed)"))
social.teci.world didn't declare any extended description!
Extended description found for social.sdf.org
Error for instance: ak.noleron.com
HTTPSConnectionPool(host='ak.noleron.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232550DD0>: Failed to resolve 'ak.noleron.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for ezone.fun
Extended description found for hhmx.de
Extended description found for mastodon.pepicrft.me
Extended description found for efdn.club
Extended description found for spore.social
Extended description found for mastoot.fr
Extended description found for mastodon.in.th
Error for instance: yorishiro.space
HTTPSConnectionPool(host='yorishiro.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1A8D0>: Failed to resolve 'yorishiro.space' ([Errno 11001] getaddrinfo failed)"))
Error for instance: norimono.moe
HTTPSConnectionPool(host='norimono.moe', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324310D0>: Failed to resolve 'norimono.moe' ([Errno 11001] getaddrinfo failed)"))
Extended description found for ma.fono.jp
Extended description found for paperbay.org
Extended description found for mastoscat.club
Error for instance: gaypirates.club
Expecting value: line 1 column 1 (char 0)
Extended description found for mikecoats.social
Extended description found for fabler.su
Extended description found for berlin.social
Error for instance: tebukuro.xyz
HTTPSConnectionPool(host='tebukuro.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D32A50>: Failed to resolve 'tebukuro.xyz' ([Errno 11001] getaddrinfo failed)"))
Extended description found for i1.no
Extended description found for tooting.ch
Extended description found for mastodon.gremlins.eu
Extended description found for mastodon.gatewayy.net
Extended description found for boing.world
Extended description found for mastodon.infodocs.eu
Error for instance: mastodon.stefofficiel.me
HTTPSConnectionPool(host='mastodon.stefofficiel.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2322589B0>, 'Connection to mastodon.stefofficiel.me timed out. (connect timeout=19)'))
Error for instance: cincy.social
HTTPSConnectionPool(host='cincy.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for snapp.social
Extended description found for coolmathgam.es
Error for instance: masto.goblackcat.net
HTTPSConnectionPool(host='masto.goblackcat.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B11C0>: Failed to resolve 'masto.goblackcat.net' ([Errno 11001] getaddrinfo failed)"))
Error for instance: frenetic.ink
HTTPSConnectionPool(host='frenetic.ink', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B34D0>: Failed to resolve 'frenetic.ink' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.fifteen40.com
Extended description found for mastodon.slightlycyberpunk.com
Extended description found for dom.ke
Extended description found for kirakiratter.com
Error for instance: itmgitmo.com
HTTPSConnectionPool(host='itmgitmo.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232189520>: Failed to resolve 'itmgitmo.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for syasai.club
Error for instance: howcyborgs.chat
HTTPSConnectionPool(host='howcyborgs.chat', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324306B0>: Failed to resolve 'howcyborgs.chat' ([Errno 11001] getaddrinfo failed)"))
Extended description found for rigor-mortis.nmrc.org
Extended description found for hydaelyn.coerthansnowstorm.online
Extended description found for samenet.social
Error for instance: mastodon-pa.sorbonne-universite.fr
HTTPSConnectionPool(host='mastodon-pa.sorbonne-universite.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1E50>: Failed to resolve 'mastodon-pa.sorbonne-universite.fr' ([Errno 11001] getaddrinfo failed)"))
Extended description found for evilcyberhacker.net
Extended description found for don.mamemo.online
Extended description found for social.sceneworld.org
Extended description found for masto.empresasenegocios.com.br
Error for instance: paypig.org
HTTPSConnectionPool(host='paypig.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Extended description found for manitu.social
Extended description found for publicsquare.global
Error for instance: komuna.digital
Expecting value: line 1 column 1 (char 0)
pixelfed.au didn't declare any extended description!
Extended description found for deacon.social
Error for instance: palinoia.xyz
HTTPSConnectionPool(host='palinoia.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D32B70>: Failed to resolve 'palinoia.xyz' ([Errno 11001] getaddrinfo failed)"))
Extended description found for cyberfurz.social
Error for instance: lol.camp
HTTPSConnectionPool(host='lol.camp', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
Extended description found for mathstodon.xyz
Extended description found for linuxhotel.social
Error for instance: luemy.eu
HTTPSConnectionPool(host='luemy.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2323E7E60>, 'Connection to luemy.eu timed out. (connect timeout=19)'))
Error for instance: conchrepublic.social
HTTPSConnectionPool(host='conchrepublic.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232468F20>: Failed to resolve 'conchrepublic.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: toot.ozor.es
HTTPSConnectionPool(host='toot.ozor.es', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232469910>: Failed to resolve 'toot.ozor.es' ([Errno 11001] getaddrinfo failed)"))
Extended description found for machikadon.online
Extended description found for tooot.im
Error for instance: isosceles.love
HTTPSConnectionPool(host='isosceles.love', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D328D0>: Failed to resolve 'isosceles.love' ([Errno 11001] getaddrinfo failed)"))
Error for instance: hub.heraut.eu
HTTPSConnectionPool(host='hub.heraut.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232468590>: Failed to resolve 'hub.heraut.eu' ([Errno 11001] getaddrinfo failed)"))
Extended description found for ginpatu.moe
Extended description found for josa.social
Extended description found for mastodon.ethibox.fr
Extended description found for jmm.kr
Extended description found for eimsbuettel.social
Extended description found for mastodon.balamb.fr
Extended description found for otter.garden
jam.xwx.moe didn't declare any extended description!
Extended description found for gloria.social
Extended description found for ohnepunktundkomma.org
Extended description found for ist-ur.org
Error for instance: weedyverse.de
HTTPSConnectionPool(host='weedyverse.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232258740>: Failed to resolve 'weedyverse.de' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.yakshed.org
Error for instance: mk.cybre.ninja
HTTPSConnectionPool(host='mk.cybre.ninja', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2321B3680>, 'Connection to mk.cybre.ninja timed out. (connect timeout=19)'))
Extended description found for ferrovipath.es
Error for instance: nullspace.ie
HTTPSConnectionPool(host='nullspace.ie', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232432AB0>, 'Connection to nullspace.ie timed out. (connect timeout=19)'))
Extended description found for xarxa.cloud
Extended description found for tau-ceti.space
Extended description found for psyopshop.com
Error for instance: helladoge.com
HTTPSConnectionPool(host='helladoge.com', port=443): Read timed out. (read timeout=10)

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

Error for instance: oarsport.social
HTTPSConnectionPool(host='oarsport.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246A210>: Failed to resolve 'oarsport.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: micro.inflo.ws
HTTPSConnectionPool(host='micro.inflo.ws', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232469C40>: Failed to resolve 'micro.inflo.ws' ([Errno 11001] getaddrinfo failed)"))
Error for instance: humangenetics.social
HTTPSConnectionPool(host='humangenetics.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C84140>: Failed to resolve 'humangenetics.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.plus.yt
Error for instance: harpia.red
Expecting value: line 1 column 1 (char 0)
Error for instance: hub.disroot.org
HTTPSConnectionPool(host='hub.disroot.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1A330>: Failed to resolve 'hub.disroot.org' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mstdn.doern.tech
HTTPSConnectionPool(host='mstdn.doern.tech', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C56FC0>: Failed to resolve 'mstdn.doern.tech' ([Errno 11001] getaddrinfo failed)"))
Extended description found for blop.social
Extended description found for social.lemee.co
Error for instance: sanjuans.life
HTTPSConnectionPool(host='sanjuans.life', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324D8650>: Failed to resolve 'sanjuans.life' ([Errno 11001] getaddrinfo failed)"))
Extended description found for queralt.social
Extended description found for hostux.social
Extended description found for rollenspiel.social
Error for instance: pentacl.es
HTTPSConnectionPool(host='pentacl.es', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324ABCB0>: Failed to resolve 'pentacl.es' ([Errno 11001] getaddrinfo failed)"))
Extended description found for weird.autos
Extended description found for social.kharkiv.dcomm.net.ua
Extended description found for rockcd.jp
Extended description found for scoat.es
Error for instance: mastodonte.quebec
HTTPSConnectionPool(host='mastodonte.quebec', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246A330>: Failed to resolve 'mastodonte.quebec' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.insa.lol
Error for instance: home.social
Expecting value: line 1 column 1 (char 0)
Extended description found for zeroes.ca
Extended description found for mastodon.sboots.ca
Extended description found for tekkadon.manimani.cc
Error for instance: fedi.club
HTTPSConnectionPool(host='fedi.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324AA690>: Failed to resolve 'fedi.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.groene.nl
Error for instance: babymetal.party
HTTPSConnectionPool(host='babymetal.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232433E60>: Failed to resolve 'babymetal.party' ([Errno 11002] getaddrinfo failed)"))
internaluse.net didn't declare any extended description!
Error for instance: queerfem.space
HTTPSConnectionPool(host='queerfem.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324DA270>: Failed to resolve 'queerfem.space' ([Errno 11001] getaddrinfo failed)"))
Extended description found for dju.social
Error for instance: uoh.cx
HTTPSConnectionPool(host='uoh.cx', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2325520F0>: Failed to resolve 'uoh.cx' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.galileivr.org
Error for instance: narwhal.pub
HTTPSConnectionPool(host='narwhal.pub', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D32E10>: Failed to resolve 'narwhal.pub' ([Errno 11001] getaddrinfo failed)"))
Error for instance: pleroma.libretux.com
HTTPSConnectionPool(host='pleroma.libretux.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D33B90>: Failed to resolve 'pleroma.libretux.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for t.chadole.com
Extended description found for social.vivaldi.net
Extended description found for hkc.social
Extended description found for otogamer.me
Error for instance: madscientists.social
HTTPSConnectionPool(host='madscientists.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323916D0>: Failed to resolve 'madscientists.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for woodworking.group
Error for instance: eupublic.social
Expecting value: line 1 column 1 (char 0)
Extended description found for social.caa-ins.org
Extended description found for trunk.mad-scientist.club
Error for instance: fedi.niklas.network
HTTPSConnectionPool(host='fedi.niklas.network', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for ma.fellr.net
Extended description found for pinkorange.red
Extended description found for mastochist.social
Extended description found for meowstodon.net
Extended description found for toot.monny.cloud
Error for instance: craftbeer.social
Expecting value: line 1 column 1 (char 0)
Extended description found for chat.trueffzido.de
Error for instance: mastodon.lol
HTTPSConnectionPool(host='mastodon.lol', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232391520>: Failed to resolve 'mastodon.lol' ([Errno 11001] getaddrinfo failed)"))
Extended description found for fuerth.social
Extended description found for innoq.social
Extended description found for rheinhessen.social
Extended description found for underwear.social
Extended description found for mastodon.beer
Error for instance: mastodon.huma-num.fr
HTTPSConnectionPool(host='mastodon.huma-num.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324A8CB0>: Failed to resolve 'mastodon.huma-num.fr' ([Errno 11001] getaddrinfo failed)"))
Error for instance: comms.thedigitallancabin.net
Expecting value: line 1 column 1 (char 0)
Extended description found for h-i.social
Extended description found for i.wildserver.ru
Extended description found for mastoxiv.page
Extended description found for travel-friends.chat
Extended description found for zusammenkunft.net
Error for instance: masto.gundan.es
Expecting value: line 1 column 1 (char 0)
Error for instance: barcelona.social
HTTPSConnectionPool(host='barcelona.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232432630>: Failed to resolve 'barcelona.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.conii.co
Error for instance: social.solibre.de
HTTPSConnectionPool(host='social.solibre.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.solibre.de'. (_ssl.c:1000)")))
Error for instance: tooters.wtf
HTTPSConnectionPool(host='tooters.wtf', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C554F0>: Failed to resolve 'tooters.wtf' ([Errno 11001] getaddrinfo failed)"))
Error for instance: playvicious.social
Expecting value: line 1 column 1 (char 0)
pixel.tchncs.de didn't declare any extended description!
Extended description found for brotkru.me
Extended description found for terra.incognita.net
Error for instance: moth.social
HTTPSConnectionPool(host='moth.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Error for instance: mitra.kemitix.net
'rules'
Error for instance: awoo.studio
HTTPSConnectionPool(host='awoo.studio', port=443): Read timed out. (read timeout=10)
Extended description found for kirche.social
Error for instance: ravearizona.club
HTTPSConnectionPool(host='ravearizona.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323923F0>: Failed to resolve 'ravearizona.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.wilboard.nl
Extended description found for social.politicaconciencia.org
dvd.chat didn't declare any extended description!
Error for instance: senky.social
HTTPSConnectionPool(host='senky.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324302C0>: Failed to resolve 'senky.social' ([Errno 11001] getaddrinfo failed)"))
clubcyberia.co didn't declare any extended description!
Extended description found for mastodon.publicinterest.town
Error for instance: nekomimi.yokohama
HTTPSConnectionPool(host='nekomimi.yokohama', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C542F0>: Failed to resolve 'nekomimi.yokohama' ([Errno 11001] getaddrinfo failed)"))
Error for instance: sigterm.wtf
HTTPSConnectionPool(host='sigterm.wtf', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232468D10>: Failed to resolve 'sigterm.wtf' ([Errno 11001] getaddrinfo failed)"))
Extended description found for photog.social
Error for instance: mao.daizhige.org
HTTPSConnectionPool(host='mao.daizhige.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C545F0>: Failed to resolve 'mao.daizhige.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for coywolf.social
Error for instance: afu.social
HTTPSConnectionPool(host='afu.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D00B90>: Failed to resolve 'afu.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: asocial.jacquesetmichel.fr
HTTPSConnectionPool(host='asocial.jacquesetmichel.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232392900>: Failed to resolve 'asocial.jacquesetmichel.fr' ([Errno 11001] getaddrinfo failed)"))
Extended description found for alpaka.social
Extended description found for social.fischbyte.de
Extended description found for omg.wtf.sh
Error for instance: akko.disqordia.space
HTTPSConnectionPool(host='akko.disqordia.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C554C0>: Failed to resolve 'akko.disqordia.space' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.skrasek.us
Extended description found for mastodon.ie
Extended description found for hom.ph
Error for instance: bottom.team
HTTPSConnectionPool(host='bottom.team', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232432630>: Failed to resolve 'bottom.team' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.jacklinke.com
Error for instance: honey.church
HTTPSConnectionPool(host='honey.church', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B25A0>: Failed to resolve 'honey.church' ([Errno 11001] getaddrinfo failed)"))
Extended description found for թ.չոլ.հայ
Error for instance: primarycare.app
HTTPSConnectionPool(host='primarycare.app', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232391310>, 'Connection to primarycare.app timed out. (connect timeout=19)'))
Extended description found for mcr.wtf
Extended description found for dz.social
Error for instance: schnauzergang.online
HTTPSConnectionPool(host='schnauzergang.online', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23246BB60>: Failed to resolve 'schnauzergang.online' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.execbase.net
Extended description found for datachimps.eu
Extended description found for payravi.xyz
Error for instance: pixel.livellosegreto.it
HTTPSConnectionPool(host='pixel.livellosegreto.it', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for fedi.halcyon-is.land
Extended description found for turath.tn
Extended description found for cathode.church
Extended description found for thecooltable.wtf
Error for instance: social.unanargeek.xyz
HTTPSConnectionPool(host='social.unanargeek.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D331A0>: Failed to resolve 'social.unanargeek.xyz' ([Errno 11001] getaddrinfo failed)"))
Extended description found for dook.business
Error for instance: theexpan.se
HTTPSConnectionPool(host='theexpan.se', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for overgrown.garden
Extended description found for toots.niark.nexus
Extended description found for social.dnitza.com
Error for instance: forms.community
HTTPSConnectionPool(host='forms.community', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
Extended description found for cultur.social
Error for instance: m.selden.page
HTTPSConnectionPool(host='m.selden.page', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232430D40>, 'Connection to m.selden.page timed out. (connect timeout=19)'))
Extended description found for twitter.resolvt.net
Extended description found for toot.earth
Extended description found for onlyfranz.com
Error for instance: nugen.me
HTTPSConnectionPool(host='nugen.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324DA7B0>: Failed to resolve 'nugen.me' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.toplap.org
Extended description found for mastodon.satoshishop.de
Extended description found for mastodon.falconk.rocks
Extended description found for mastodon.underworld.fr
Extended description found for gs.leftic.club
Error for instance: mobiliteactive.org
HTTPSConnectionPool(host='mobiliteactive.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mobiliteactive.org'. (_ssl.c:1000)")))
Error for instance: gnusocial.de
HTTPSConnectionPool(host='gnusocial.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'gnusocial.de'. (_ssl.c:1000)")))
Extended description found for nso.group
Error for instance: catgirl.science
HTTPSConnectionPool(host='catgirl.science', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B01BB0>, 'Connection to catgirl.science timed out. (connect timeout=19)'))
Error for instance: ricearoni.org
HTTPSConnectionPool(host='ricearoni.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E2324D93A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Error for instance: firefish.tenkuu.social
HTTPSConnectionPool(host='firefish.tenkuu.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2324A8620>, 'Connection to firefish.tenkuu.social timed out. (connect timeout=19)'))
Extended description found for queer.garden
Extended description found for cursoryreview.org
Extended description found for mastodon.tmm.cx
Extended description found for mastodon.no2nd.earth
Extended description found for urusai.social
Extended description found for mastodon.gruezi.net
Extended description found for mastodon.cosmicnation.co
Extended description found for social.edist.ro
Extended description found for an.errant.cloud
Extended description found for ruby.social
Extended description found for mastodon.mg
Error for instance: berserker.town
HTTPSConnectionPool(host='berserker.town', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324A91F0>: Failed to resolve 'berserker.town' ([Errno 11001] getaddrinfo failed)"))
Extended description found for gm-cloud.org.uk
Extended description found for imc.sh
Extended description found for ulmd.de
Extended description found for mastodon-belgium.be
Extended description found for standup-comics.net
Error for instance: social.cherrykitten.dev

Checking software:   0%|          | 0/1000 [00:00<?, ?it/s]

Error for instance: stop.voring.me
HTTPSConnectionPool(host='stop.voring.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323C17C0>: Failed to resolve 'stop.voring.me' ([Errno 11001] getaddrinfo failed)"))
Error for instance: woofed.me
HTTPSConnectionPool(host='woofed.me', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A92A50>: Failed to resolve 'woofed.me' ([Errno 11001] getaddrinfo failed)"))
Error for instance: volksverpetzer.social
HTTPSConnectionPool(host='volksverpetzer.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Error for instance: law-and-politics.online
HTTPSConnectionPool(host='law-and-politics.online', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'law-and-politics.online'. (_ssl.c:1000)")))
Error for instance: shaktzu.org
Expecting value: line 1 column 1 (char 0)
Error for instance: artalley.porn
HTTPSConnectionPool(host='artalley.porn', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232B369C0>: Failed to resolve 'artalley.porn' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.undeadnetwork.de
Extended description found for mastodon.hk
Extended description found for pouet.chapril.org
Extended description found for eloi.social
Extended description found for library.love
Error for instance: nzserver.co
HTTPSConnectionPool(host='nzserver.co', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B1640>: Failed to resolve 'nzserver.co' ([Errno 11001] getaddrinfo failed)"))
Extended description found for kde.social
Extended description found for social.design.systems
Error for instance: lewd.cx
HTTPSConnectionPool(host='lewd.cx', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232553770>: Failed to resolve 'lewd.cx' ([Errno 11001] getaddrinfo failed)"))
Error for instance: turtle.pizza
Expecting value: line 1 column 1 (char 0)
Extended description found for social.spejset.org
Extended description found for spezi.social
Extended description found for mastodon.spotek.io
Extended description found for kinkycats.org
Extended description found for publicidentity.net
Error for instance: ongardenroad.ca
HTTPSConnectionPool(host='ongardenroad.ca', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A91A60>: Failed to resolve 'ongardenroad.ca' ([Errno 11001] getaddrinfo failed)"))
Extended description found for fediunam.site
Error for instance: fandom.community
HTTPSConnectionPool(host='fandom.community', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B3470>: Failed to resolve 'fandom.community' ([Errno 11001] getaddrinfo failed)"))
Error for instance: calckey.online
Expecting value: line 1 column 1 (char 0)
Error for instance: mastodon.blackbike.us
HTTPSConnectionPool(host='mastodon.blackbike.us', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B3290>: Failed to resolve 'mastodon.blackbike.us' ([Errno 11001] getaddrinfo failed)"))
Extended description found for dial.modem.show
Extended description found for social.drastical.tech
Extended description found for oulipo.social
Extended description found for mastodon.hongkongers.net
Extended description found for jkpg.rocks
Error for instance: onemorestop.photo
HTTPSConnectionPool(host='onemorestop.photo', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2321B05C0>: Failed to resolve 'onemorestop.photo' ([Errno 11001] getaddrinfo failed)"))
Error for instance: hawaiidiff.com
HTTPSConnectionPool(host='hawaiidiff.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232D1E780>: Failed to resolve 'hawaiidiff.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.tod.net
gleasonator.com didn't declare any extended description!
Extended description found for burn.capital
Error for instance: megadon.net
HTTPSConnectionPool(host='megadon.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232552D20>: Failed to resolve 'megadon.net' ([Errno 11001] getaddrinfo failed)"))
Extended description found for fediverse.science
Extended description found for mstdn.ca
Extended description found for blat.at
Extended description found for awjeez.help
Extended description found for notvery.social
Error for instance: toots.benpro.fr
HTTPSConnectionPool(host='toots.benpro.fr', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B02C90>: Failed to resolve 'toots.benpro.fr' ([Errno 11001] getaddrinfo failed)"))
Error for instance: nutmeg.social
HTTPSConnectionPool(host='nutmeg.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C85730>: Failed to resolve 'nutmeg.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: chat.wecops.uk
HTTPSConnectionPool(host='chat.wecops.uk', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'chat.wecops.uk'. (_ssl.c:1000)")))
Extended description found for hpi.social
Error for instance: mastodonsuomi.fi
HTTPSConnectionPool(host='mastodonsuomi.fi', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2323C0D40>: Failed to resolve 'mastodonsuomi.fi' ([Errno 11001] getaddrinfo failed)"))
Error for instance: hawthorn.pub
HTTPSConnectionPool(host='hawthorn.pub', port=443): Read timed out. (read timeout=10)
Extended description found for technodon.org
Extended description found for owo.ff15.eu
nightshift.social didn't declare any extended description!
Extended description found for kogumus.masto.host
birdity.club didn't declare any extended description!
Extended description found for toot.ikata.co
Extended description found for shakedown.social
Extended description found for soc.nochn.net
Error for instance: dubnation.social
HTTPSConnectionPool(host='dubnation.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
Extended description found for ljs.social
Extended description found for tabletop.social
Error for instance: mastodon.kf0are.net
HTTPSConnectionPool(host='mastodon.kf0are.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2325503E0>: Failed to resolve 'mastodon.kf0are.net' ([Errno 11001] getaddrinfo failed)"))
Error for instance: eggplant.social
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Error for instance: calckey.social
HTTPSConnectionPool(host='calckey.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231C84230>, 'Connection to calckey.social timed out. (connect timeout=19)'))
Error for instance: welovela.in
HTTPSConnectionPool(host='welovela.in', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232C896A0>: Failed to resolve 'welovela.in' ([Errno 11001] getaddrinfo failed)"))
Error for instance: mastodon.sxpert.org
HTTPSConnectionPool(host='mastodon.sxpert.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2323C0BC0>, 'Connection to mastodon.sxpert.org timed out. (connect timeout=19)'))
Extended description found for kish.social
Extended description found for hola-soy-milk.online
Error for instance: thms.uk
Expecting value: line 1 column 1 (char 0)
Extended description found for social.dytrych.cloud
Extended description found for mastodon.alexnackenoff.com
Extended description found for kulturfront.org
Extended description found for 73-110.pl
Error for instance: terradaliberdade.pt
HTTPSConnectionPool(host='terradaliberdade.pt', port=443): Read timed out. (read timeout=10)
Error for instance: meep.tech
HTTPSConnectionPool(host='meep.tech', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2323C3830>, 'Connection to meep.tech timed out. (connect timeout=19)'))
Extended description found for romeros.link
Error for instance: shbgm.space
HTTPSConnectionPool(host='shbgm.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CAA030>: Failed to resolve 'shbgm.space' ([Errno 11001] getaddrinfo failed)"))
pix.diaspodon.fr didn't declare any extended description!
Extended description found for social.globalpirates.net
Extended description found for universeodon.com
Error for instance: social.umeahackerspace.se
HTTPSConnectionPool(host='social.umeahackerspace.se', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231CA9820>: Failed to resolve 'social.umeahackerspace.se' ([Errno 11001] getaddrinfo failed)"))
Error for instance: cute.lolison.top
HTTPSConnectionPool(host='cute.lolison.top', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232C89C10>: Failed to resolve 'cute.lolison.top' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.grautier.com
HTTPSConnectionPool(host='social.grautier.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.grautier.com'. (_ssl.c:1000)")))
Extended description found for meshed.cloud
Extended description found for flokinet.social
Extended description found for lily.network
Extended description found for lustigetiernamenbubble.de
Extended description found for gochisou.photo
Extended description found for merveilles.town
Extended description found for pepple.us
Error for instance: genealogy.socialExtended description found for mastodon.ellipsis.fi

HTTPSConnectionPool(host='genealogy.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232B34650>: Failed to resolve 'genealogy.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: ck.katzen.cafe
HTTPSConnectionPool(host='ck.katzen.cafe', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'ck.katzen.cafe'. (_ssl.c:1000)")))
Error for instance: cfultz.com
HTTPSConnectionPool(host='cfultz.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2325508F0>, 'Connection to cfultz.com timed out. (connect timeout=19)'))
Error for instance: neuromatch.social
HTTPSConnectionPool(host='neuromatch.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232B11CD0>, 'Connection to neuromatch.social timed out. (connect timeout=19)'))
Extended description found for types.pl
Extended description found for social.v.st
Error for instance: muffin.pm
HTTPSConnectionPool(host='muffin.pm', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232553FE0>: Failed to resolve 'muffin.pm' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.queer-lexikon.net
Extended description found for mascodon.jp
Extended description found for o0o.social
Extended description found for swiss.social
Extended description found for mastodon.hypnoguys.com
Error for instance: fedi.transgendershitposting.com
HTTPSConnectionPool(host='fedi.transgendershitposting.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for todon.nl
Extended description found for social.coletivos.org
Extended description found for daedal.io
Error for instance: overkill.social
HTTPSConnectionPool(host='overkill.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for masto.ink
Extended description found for mastodon.blaster.com.ar
Extended description found for ohbear.wtf
Extended description found for essjax.com
Extended description found for mastodon.acc.sunet.se
Error for instance: social.chvp.be
HTTPSConnectionPool(host='social.chvp.be', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324C6360>: Failed to resolve 'social.chvp.be' ([Errno 11001] getaddrinfo failed)"))
Extended description found for objc.social
Error for instance: saltwatercity.org
HTTPSConnectionPool(host='saltwatercity.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E2324C5700>: Failed to resolve 'saltwatercity.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for graphics.social
Error for instance: vorarlberg.io
HTTPSConnectionPool(host='vorarlberg.io', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1000)')))
idtech.space didn't declare any extended description!
Extended description found for sachsen-medien.social
Error for instance: masto.recknsense.com
HTTPSConnectionPool(host='masto.recknsense.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'masto.recknsense.com'. (_ssl.c:1000)")))
Error for instance: med-mammoth.com
HTTPSConnectionPool(host='med-mammoth.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E2324C4FB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for mastodonapp.uk
Extended description found for okla.social
Error for instance: sleeping.town
Expecting value: line 1 column 1 (char 0)
Error for instance: pla.social
HTTPSConnectionPool(host='pla.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232B37B90>: Failed to resolve 'pla.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for beautifullosers.org
Extended description found for veganism.social
Extended description found for bgme.me
Extended description found for cloudisland.nz
Error for instance: mastodon.yumulab.org
HTTPSConnectionPool(host='mastodon.yumulab.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C86660>: Failed to resolve 'mastodon.yumulab.org' ([Errno 11001] getaddrinfo failed)"))
Extended description found for masto.deluma.biz
Extended description found for rants.au
Extended description found for flumph.masto.host
Error for instance: somnium.fi
HTTPSConnectionPool(host='somnium.fi', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231D30E60>: Failed to resolve 'somnium.fi' ([Errno 11001] getaddrinfo failed)"))
Extended description found for bunt.social
Extended description found for hsnl.social
Extended description found for blacktwitter.io
Extended description found for photodn.net
Extended description found for a11y.social
Error for instance: notbird.site
Expecting value: line 1 column 1 (char 0)
Extended description found for mastodon.stickbear.me
Extended description found for soziale.cloud
Extended description found for gamedev.lgbtpixel.pol.social didn't declare any extended description!

Error for instance: rafting.io
HTTPSConnectionPool(host='rafting.io', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E2323C3860>, 'Connection to rafting.io timed out. (connect timeout=19)'))
Extended description found for fikaverse.club
Extended description found for discordian.social
Error for instance: iddqd.social
HTTPSConnectionPool(host='iddqd.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232B361E0>, 'Connection to iddqd.social timed out. (connect timeout=19)'))
Extended description found for lgbt.io
Extended description found for cultiv.social
Extended description found for cozymech.com
Extended description found for brocks.social
Error for instance: halifaxsocial.ca
HTTPSConnectionPool(host='halifaxsocial.ca', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C56B70>: Failed to resolve 'halifaxsocial.ca' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mastodon.fsinf.at
Error for instance: hoot-n-tea.art
HTTPSConnectionPool(host='hoot-n-tea.art', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231C56750>: Failed to resolve 'hoot-n-tea.art' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mstdn.gamercast.net
Extended description found for toot.io
Extended description found for katzebot.space
Error for instance: proudrebels.me
Expecting value: line 1 column 1 (char 0)
Error for instance: neurospicy.club

Checking software:   0%|          | 0/199 [00:00<?, ?it/s]

Extended description found for sbg-social.at
Extended description found for drg.nz
Extended description found for hostsharing.coop
Extended description found for corneill.es
Error for instance: screengeeks.club
HTTPSConnectionPool(host='screengeeks.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232D94AD0>: Failed to resolve 'screengeeks.club' ([Errno 11001] getaddrinfo failed)"))
Error for instance: dancingbanana.party
HTTPSConnectionPool(host='dancingbanana.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232DF52E0>: Failed to resolve 'dancingbanana.party' ([Errno 11001] getaddrinfo failed)"))
Error for instance: social.calidris.lv
HTTPSConnectionPool(host='social.calidris.lv', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'social.calidris.lv'. (_ssl.c:1000)")))
Extended description found for researchbuzz.masto.host
Extended description found for flyovercountry.social
Extended description found for social.harter.us
Error for instance: comerocudequemestalendo.com
HTTPSConnectionPool(host='comerocudequemestalendo.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232D94830>: Failed to resolve 'comerocudequemestalendo.com' ([Errno 11001] getaddrinfo failed)"))
Extended description found for social.ei8fdb.org
Error for instance: hlidacstatu.social
HTTPSConnectionPool(host='hlidacstatu.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232550D70>: Failed to resolve 'hlidacstatu.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for retro.social
Extended description found for mastouille.fr
Extended description found for physchem.science
Extended description found for mel.social
Extended description found for homo.dev
Error for instance: marxism.party
HTTPSConnectionPool(host='marxism.party', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232DF6F60>: Failed to resolve 'marxism.party' ([Errno 11001] getaddrinfo failed)"))
Extended description found for muenster.im
Extended description found for maaw.social
Extended description found for aethy.com
Extended description found for anti-social.online
Extended description found for vacatureforum.nl
Error for instance: mastodon.westsideblogger.eu
HTTPSConnectionPool(host='mastodon.westsideblogger.eu', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1000)')))
Error for instance: kursors.social
HTTPSConnectionPool(host='kursors.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232DDADE0>: Failed to resolve 'kursors.social' ([Errno 11001] getaddrinfo failed)"))
Error for instance: 3rdstone.cc
Expecting value: line 1 column 1 (char 0)
Extended description found for radikal.social
Extended description found for social.modest.com
Error for instance: distrotoot.com
HTTPSConnectionPool(host='distrotoot.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'distrotoot.com'. (_ssl.c:1000)")))
Extended description found for fedihum.org
Extended description found for mastodon.vlaanderen
Error for instance: butts.masto.host
HTTPSConnectionPool(host='butts.masto.host', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for wpmastodon.es
Extended description found for bbiz.io
Extended description found for philly.vs-the.world
Extended description found for instancia.org
Error for instance: herds.eu
Expecting value: line 1 column 1 (char 0)
Error for instance: ypolis.net
HTTPSConnectionPool(host='ypolis.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232E10470>: Failed to resolve 'ypolis.net' ([Errno 11001] getaddrinfo failed)"))
Extended description found for f.freinetz.ch
Extended description found for mspsocial.net
Error for instance: social.dib.de
HTTPSConnectionPool(host='social.dib.de', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23218A750>: Failed to resolve 'social.dib.de' ([Errno 11001] getaddrinfo failed)"))
Error for instance: margio.in
HTTPSConnectionPool(host='margio.in', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232431340>: Failed to resolve 'margio.in' ([Errno 11001] getaddrinfo failed)"))
Extended description found for dreamin.online
Extended description found for vhs.social
Error for instance: jammer.social
HTTPSConnectionPool(host='jammer.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.val-sans-retour.fr
Extended description found for minamina3710.com
Extended description found for social.mottokrosh.com
Extended description found for meh.social
Extended description found for ticos.social
Error for instance: toot.site
HTTPSConnectionPool(host='toot.site', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231A93260>: Failed to resolve 'toot.site' ([Errno 11001] getaddrinfo failed)"))
Error for instance: nederland.online
HTTPSConnectionPool(host='nederland.online', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'nederland.online'. (_ssl.c:1000)")))
Extended description found for social.wastedalpaca.wtf
Extended description found for sharetron.com
Error for instance: friendica.feneas.org
HTTPSConnectionPool(host='friendica.feneas.org', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232E12B70>: Failed to resolve 'friendica.feneas.org' ([Errno 11001] getaddrinfo failed)"))
Error for instance: waifuappreciation.club
HTTPSConnectionPool(host='waifuappreciation.club', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E23218A360>: Failed to resolve 'waifuappreciation.club' ([Errno 11001] getaddrinfo failed)"))
Extended description found for phpc.social
Extended description found for lesbian.solutions
pixelfed.fi didn't declare any extended description!
Error for instance: weirdo.network
Expecting value: line 1 column 1 (char 0)
Error for instance: morse.haus
HTTPSConnectionPool(host='morse.haus', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232E10B30>: Failed to resolve 'morse.haus' ([Errno 11001] getaddrinfo failed)"))
Extended description found for neurodifferent.me
Extended description found for social.kaoskvlt.de
Extended description found for verified.mastodonmedia.xyz
Error for instance: turingfesten.dk
HTTPSConnectionPool(host='turingfesten.dk', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for social.zym.lol
Extended description found for wrong.tools
Error for instance: quite.lewd.today
HTTPSConnectionPool(host='quite.lewd.today', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232E130B0>: Failed to resolve 'quite.lewd.today' ([Errno 11001] getaddrinfo failed)"))
Error for instance: loli.pizza
Expecting value: line 1 column 1 (char 0)
Extended description found for social.bim.land
Extended description found for dice.camp
Extended description found for hactivedirectory.com
Extended description found for pertsch.social
Error for instance: social.lovetux.net
HTTPSConnectionPool(host='social.lovetux.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B19040>: Failed to resolve 'social.lovetux.net' ([Errno 11001] getaddrinfo failed)"))
Extended description found for toot.yosh.is
Extended description found for social.hnnng.space
Extended description found for yyc.bike
Error for instance: misskey.cf
HTTPSConnectionPool(host='misskey.cf', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B1BD70>: Failed to resolve 'misskey.cf' ([Errno 11001] getaddrinfo failed)"))
Extended description found for anticapitalist.party
Extended description found for mstdn.love
Extended description found for fedi.kcore.org
Extended description found for india.goonj.xyz
Extended description found for hemmer.land
Extended description found for gay.camera
Extended description found for pixelig.social
Extended description found for bundyo.com
Extended description found for mastodon.bizarreworker.de
Extended description found for mastodon.gougere.fr
Extended description found for beppo.online
Error for instance: gbtdn.tokyo
HTTPSConnectionPool(host='gbtdn.tokyo', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232432DE0>: Failed to resolve 'gbtdn.tokyo' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mstdn.chrisalemany.ca
Error for instance: social.lovingexpressions.net
HTTPSConnectionPool(host='social.lovingexpressions.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001E232189AF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
Extended description found for astronomy.social
Extended description found for bifrost.berzerk.pl
Error for instance: mastnode.faith
HTTPSConnectionPool(host='mastnode.faith', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for arthropod.social
Error for instance: unmute.community
HTTPSConnectionPool(host='unmute.community', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B018E0>: Failed to resolve 'unmute.community' ([Errno 11001] getaddrinfo failed)"))
Extended description found for nondeterministic.computer
Extended description found for nora.social
Extended description found for phparch.social
Extended description found for pan.rent
Extended description found for social.butnot.today
Extended description found for social.kechpaja.com
Extended description found for genealysis.social
Extended description found for wonkodon.com
Extended description found for mn.siru.tokyo
Extended description found for mastodon.cesko.digital
Extended description found for space.jeroenvd.nl
Extended description found for epicure.social
Extended description found for toon.social
Error for instance: mstdn.media
HTTPSConnectionPool(host='mstdn.media', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232E13410>: Failed to resolve 'mstdn.media' ([Errno 11001] getaddrinfo failed)"))
Extended description found for bol.social
Extended description found for khiar.net
Error for instance: pler.garrison.beer
HTTPSConnectionPool(host='pler.garrison.beer', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B4E5A0>: Failed to resolve 'pler.garrison.beer' ([Errno 11001] getaddrinfo failed)"))
Error for instance: robot.rodeo
HTTPSConnectionPool(host='robot.rodeo', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1000)')))
Extended description found for tukkers.online
Extended description found for aschaffenburg.social
Extended description found for denden.world
Extended description found for a17k.social
Extended description found for atx.pub
Extended description found for klog.tw
Extended description found for mastodon.chateaude.luxe
Extended description found for latenight.social
Error for instance: snooter.space
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Extended description found for hypno.social
Error for instance: renkontu.com
Expecting value: line 3 column 1 (char 4)
Error for instance: social.undernet.uy
HTTPSConnectionPool(host='social.undernet.uy', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E232433A70>: Failed to resolve 'social.undernet.uy' ([Errno 11001] getaddrinfo failed)"))
Extended description found for cybercuties.net
Extended description found for newwest.social
Extended description found for rcsocial.net
Error for instance: jonmasters.social
HTTPSConnectionPool(host='jonmasters.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))
Extended description found for nfb.social
Extended description found for social.karotte.org
Extended description found for social.medusmedia.com
Error for instance: 0sint.social
HTTPSConnectionPool(host='0sint.social', port=443): Max retries exceeded with url: /api/v2/instance (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001E231B19310>: Failed to resolve '0sint.social' ([Errno 11001] getaddrinfo failed)"))
Extended description found for mrrob.in
Extended description found for polyglot.city
Error for instance: tuxspace.net
Exceeded 30 redirects.
Error for instance: pub.mayel.space
HTTPSConnectionPool(host='pub.mayel.space', port=443): Max retries exceeded with url: /api/v2/instance (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'pub.mayel.space'. (_ssl.c:1000)")))
Extended description found for wx.social
Extended description found for mastodontti.fi
Extended description found for banjo.town
Extended description found for gazuji.com
Extended description found for glauca.space
Extended description found for masto.kix2902.dev
Extended description found for oceanplayground.social
Error for instance: gyptazy.ch
HTTPSConnectionPool(host='gyptazy.ch', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232E13AA0>, 'Connection to gyptazy.ch timed out. (connect timeout=19)'))
Error for instance: sn.angry.im
HTTPSConnectionPool(host='sn.angry.im', port=443): Read timed out. (read timeout=10)
Error for instance: mastodon.to
HTTPSConnectionPool(host='mastodon.to', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232E10EF0>, 'Connection to mastodon.to timed out. (connect timeout=19)'))
Error for instance: isthelaststop.com
HTTPSConnectionPool(host='isthelaststop.com', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231D010D0>, 'Connection to isthelaststop.com timed out. (connect timeout=19)'))
Error for instance: toot.smwhr.net
HTTPSConnectionPool(host='toot.smwhr.net', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E232CCE180>, 'Connection to toot.smwhr.net timed out. (connect timeout=19)'))
Error for instance: subs4social.xyz
HTTPSConnectionPool(host='subs4social.xyz', port=443): Max retries exceeded with url: /api/v2/instance (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E231B424B0>, 'Connection to subs4social.xyz timed out. (connect timeout=19)'))
Instances checked:  5112

In [14]:
# Creating dataframe from results
df_info = pd.DataFrame(results, columns=["instance", "title", "description", "extended_description", "version", "server_source", "active_users", "rules"])
df_info.head()

,instance,title,description,extended_description,version,server_source,active_users,rules
0,pleroma.lord.re,Pleroma,Monouser instance,None,2.7.2 (compatible; Pleroma 2.9.1),https://git.pleroma.social/pleroma/pleroma,2.0,[]
1,leipzig.town,leipzig.town,Hier sind alle Willkommen die Leipzig ihr zu H...,leipzigtown ist ein Angebot von Impressum Anga...,4.4.1,https://github.com/mastodon/mastodon,56.0,[Sexuell explizite oder gewalttätige Medien mü...
2,succubus.town,None,None,None,None,None,NaN,None
3,v2br.social,v2br.social,A place for vTubers their fans artists and the...,v2brsocial was created to be a place for vTube...,4.4.2,https://github.com/mastodon/mastodon,14.0,"[Don't be a jerk., No racism, sexism, homophob..."
4,social.bund.de,social.bund.de,Dies ist der MastodonServer der Bundesbeauftra...,Die Bundesbeauftragte für den Datenschutz und ...,4.3.8,https://github.com/mastodon/mastodon,98.0,[]

In [15]:
df_info.shape

(5112, 8)

In [ ]:
# Removing rows with missing values
df_info_clean = df_info.dropna()
df_info_clean.head()

,instance,title,description,extended_description,version,server_source,active_users,rules
1,leipzig.town,leipzig.town,Hier sind alle Willkommen die Leipzig ihr zu H...,leipzigtown ist ein Angebot von Impressum Anga...,4.4.1,https://github.com/mastodon/mastodon,56.0,[Sexuell explizite oder gewalttätige Medien mü...
3,v2br.social,v2br.social,A place for vTubers their fans artists and the...,v2brsocial was created to be a place for vTube...,4.4.2,https://github.com/mastodon/mastodon,14.0,"[Don't be a jerk., No racism, sexism, homophob..."
4,social.bund.de,social.bund.de,Dies ist der MastodonServer der Bundesbeauftra...,Die Bundesbeauftragte für den Datenschutz und ...,4.3.8,https://github.com/mastodon/mastodon,98.0,[]
5,fosspri.de,FossPride™,,This instance uses Mutant Standard emoji which...,4.4.2+fosspride,https://github.com/Joshix-1/mastodon/tree/v4.4...,7.0,"[be nice, don't toot illegal things, show resp..."
6,mstdn.lt,Visos upės teka,Čia suprantam lietuviškai We understand lithua...,Our small Mastodon server is managed by lithua...,4.4.2+glitch,https://github.com/glitch-soc/mastodon,41.0,[Be respectful and courteous to others at all ...

In [18]:
df_info_clean.isna().sum()

instance                0
title                   0
description             0
extended_description    0
version                 0
server_source           0
active_users            0
rules                   0
dtype: int64

In [19]:
df_info_clean.shape

(3096, 8)

In [20]:
import ast

# Convert 'rules' column from string representation to actual list of dictionaries if needed
def parse_rules(rules):
    if isinstance(rules, str):
        try:
            return ast.literal_eval(rules)
        except Exception:
            return []
    return rules

df_info_clean['rules'] = df_info_clean['rules'].apply(parse_rules)

C:\Users\alelc\AppData\Local\Temp\ipykernel_28188\1250915123.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_info_clean['rules'] = df_info_clean['rules'].apply(parse_rules)

In [21]:
df_info_clean.head()

,instance,title,description,extended_description,version,server_source,active_users,rules
1,leipzig.town,leipzig.town,Hier sind alle Willkommen die Leipzig ihr zu H...,leipzigtown ist ein Angebot von Impressum Anga...,4.4.1,https://github.com/mastodon/mastodon,56.0,[Sexuell explizite oder gewalttätige Medien mü...
3,v2br.social,v2br.social,A place for vTubers their fans artists and the...,v2brsocial was created to be a place for vTube...,4.4.2,https://github.com/mastodon/mastodon,14.0,"[Don't be a jerk., No racism, sexism, homophob..."
4,social.bund.de,social.bund.de,Dies ist der MastodonServer der Bundesbeauftra...,Die Bundesbeauftragte für den Datenschutz und ...,4.3.8,https://github.com/mastodon/mastodon,98.0,[]
5,fosspri.de,FossPride™,,This instance uses Mutant Standard emoji which...,4.4.2+fosspride,https://github.com/Joshix-1/mastodon/tree/v4.4...,7.0,"[be nice, don't toot illegal things, show resp..."
6,mstdn.lt,Visos upės teka,Čia suprantam lietuviškai We understand lithua...,Our small Mastodon server is managed by lithua...,4.4.2+glitch,https://github.com/glitch-soc/mastodon,41.0,[Be respectful and courteous to others at all ...

In [22]:
# Remove rows with no description
df_info_with_description = df_info_clean[df_info_clean['description'].notna() & (df_info_clean['description'] != '')]
print(f"Original dataframe shape: {df_info_clean.shape}")
print(f"After removing rows with no description: {df_info_with_description.shape}")
print(f"Removed {df_info_clean.shape[0] - df_info_with_description.shape[0]} rows with missing descriptions")

# Show some examples of remaining descriptions
print("\nSample descriptions:")
print(df_info_with_description['description'].head().tolist())

Original dataframe shape: (3096, 8)
After removing rows with no description: (2630, 8)
Removed 466 rows with missing descriptions

Sample descriptions:
['Hier sind alle Willkommen die Leipzig ihr zu Hause nennen undoder die Stadt lieben Bitte seid exzellent zueinander und haltet euch an die Regeln Foto von F Heiberger Pixabay', 'A place for vTubers their fans artists and the everyone else to gather share and have fun', 'Dies ist der MastodonServer der Bundesbeauftragten für den Datenschutz und die Informationsfreiheit BfDI', 'Čia suprantam lietuviškai We understand lithuanian', 'Indigenous People Hosted server for Indigenous People Culture Language banner image Nanibah']

In [ ]:
# Saving the cleaned dataset with metadata
df_info_with_description.to_csv("data/Mastodon_instances_metadata_v3.csv", index=False)